const {chromium}=require(process.env.NOVA_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
(async()=>{
 const base=path.resolve(__dirname,'..'),output=path.join(base,'.build_ui');fs.mkdirSync(output,{recursive:true});
 const data=JSON.parse(fs.readFileSync(base+'/activites-revision/data.json'));let origin;
 const server=http.createServer((req,res)=>{let p=path.join(base,decodeURIComponent(new URL(req.url,origin).pathname));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.md':'text/plain','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:740,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function open(k,st=0){await page.goto(origin+'/activites-revision/?chapitre='+k);await page.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);await page.evaluate(n=>{step=n;render();},st);assert(await page.locator('#questions').isEnabled());}
 if(!process.env.NOVA_NATIVE_ONLY)for(const [k,l]of Object.entries(data))for(let st=0;st<l.activities.length;st++){
  await open(k,st);const a=l.activities[st];assert.equal(await page.locator('.steps span').count(),l.activities.length+1);
  if(['classify','timeline'].includes(a.type)){
   const first=await page.evaluate(()=>order.join(','));await open(k,st);const second=await page.evaluate(()=>order.join(','));assert.notEqual(first,second);assert.notEqual(second,a.items.map((_,i)=>i).join(','));
   for(let i=0;i<a.items.length;i++){assert.equal(await page.locator('[data-card]').count(),1);const q=await page.evaluate(()=>lesson.activities[step].items[order[qi]]);await page.locator('[data-target]').filter({hasText:q.target}).first().click();if(i<a.items.length-1)await page.locator('#next').click();}assert(await page.evaluate(()=>stageReady));
  }else if(['cases','binary','phone','scratch','books'].includes(a.type)){
   for(let i=0;i<a.items.length;i++){const q=await page.evaluate(()=>lesson.activities[step].items[order[qi]]);
    if(a.type==='phone'){for(const n of q.answer)await page.locator('.phone-key').filter({has:page.locator('span',{hasText:new RegExp('^'+n+'$')})}).click();await page.locator('.phone-call').click();}
    else{if(a.type==='scratch')await page.getByRole('button',{name:'Découvrir sans gratter (clavier)',exact:true}).click();if(a.type==='books'){await page.locator('.book-cover').evaluate(img=>img.decode());const bytes=await (await page.request.get(origin+'/activites-revision/'+q.image)).text();assert(!bytes.includes(q.answer));await page.locator('.book-frame').screenshot({path:path.join(output,'couverture-'+path.basename(q.image,'.jpg')+'.png')});if(i===0)await page.locator('.book-frame').screenshot({path:path.join(output,'couverture.png')});}await page.getByRole('button',{name:q.answer,exact:true}).click();}
    assert(await page.evaluate(()=>answered));await page.locator('#next').click();
   }assert.equal(await page.evaluate(()=>step),st+1);
  }else if(a.type==='languages-map'){
   for(let i=0;i<a.items.length;i++){const q=await page.evaluate(()=>lesson.activities[step].items[order[qi]]);await page.locator('[data-card]').click();await page.locator('[data-target="'+q.targets[q.targets.length-1]+'"]').first().click();assert(await page.evaluate(()=>answered));if(i===0)await page.locator('#activity').screenshot({path:path.join(output,'langues.png')});await page.locator('#next').click();}assert.equal(await page.evaluate(()=>step),2);
  }else if(a.type==='select-symbols'){
   for(let i=0;i<a.items.length;i++)if(a.items[i].correct)await page.locator('[data-symbol="'+i+'"]').click();await page.getByRole('button',{name:'Valider mes choix',exact:true}).click();assert(await page.evaluate(()=>stageReady));assert.equal(await page.evaluate(()=>score),4);await page.locator('.symbol-grid').screenshot({path:path.join(output,'symboles.png')});
  }else if(a.type==='payslip-click'){
   for(let i=0;i<a.items.length;i++){const q=a.items[i];if(q.target){await page.locator('.payslip-sheet img').evaluate(img=>img.decode());await page.locator('[data-zone="'+q.target+'"]').click();if(i===0)await page.locator('.payslip-sheet').screenshot({path:path.join(output,'bulletin.png')});}else{await page.getByRole('textbox',{name:'Montant en euros'}).fill(String(q.answer).replace('.',','));await page.getByRole('button',{name:'Vérifier mon calcul',exact:true}).click();}assert(await page.evaluate(()=>answered));await page.locator('#next').click();}assert.equal(await page.evaluate(()=>step),2);assert.equal(await page.evaluate(()=>score-checkpointScore),0);assert(await page.locator('#activity').innerText().then(t=>t.includes('Vous avez obtenu un score de ')));await page.locator('#correction-button').click();assert(await page.locator('#correction').isVisible());
  }else if(a.type==='school'){
   for(let i=a.items.length-1;i>=0;i--){await page.locator('[data-card="'+i+'"]').click();await page.locator('[data-target]').filter({hasText:a.items[i].target}).first().click();}const groups=await page.locator('.destination').evaluateAll(bs=>bs.map(b=>[...b.querySelectorAll('.placed')].map(s=>Number(s.dataset.levelOrder))));groups.forEach(g=>assert.deepEqual(g,[...g].sort((a,b)=>a-b)));
  }else if(a.type==='connect'){
   const left=page.locator('[data-card="0"]'),right=page.locator('[data-target]').filter({hasText:a.items[0].target}).first();await page.locator('.connect-board').scrollIntoViewIfNeeded();const p=await left.boundingBox(),q=await right.boundingBox();await page.mouse.move(p.x+p.width-5,p.y+p.height/2);await page.mouse.down();await page.mouse.move(q.x+5,q.y+q.height/2,{steps:8});await page.mouse.up();assert(await page.evaluate(()=>placed.has(0)));assert.equal(await page.locator('.connection-lines line').count(),1);
  }else if(['scheme','care','cycle'].includes(a.type)){
   for(const item of a.items)await page.getByRole('button',{name:item.label,exact:true}).click();assert(await page.evaluate(()=>stageReady));
  }
 }
 console.log('39 activités : ordre aléatoire, nouveaux exercices, progression variable, clics sur bulletin et calculs validés.');
 await page.setViewportSize({width:390,height:844});for(const [k,l]of Object.entries(data))for(let st=0;st<l.activities.length;st++){await open(k,st);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),k+' déborde sur mobile');}console.log('39 activités à 390 px : aucun débordement horizontal.');
 await page.setViewportSize({width:740,height:950});
 await page.route('**/chat_bot.md',r=>r.fulfill({body:fs.readFileSync(base+'/chat_bot.md','utf8').replaceAll('https://codeurfou-sys.github.io/chatbot_civique2/',origin+'/'),contentType:'text/plain'}));
 await page.goto(origin+'/chatbot/?retour=SCR_REV_T5_CH04_VERIF');await page.getByRole('link',{name:'✍️ Commencer les 4 questions',exact:true}).waitFor({timeout:20000});await page.getByRole('link',{name:'✍️ Commencer les 4 questions',exact:true}).click();await page.waitForTimeout(3500);await page.locator('#user-input').fill('3 ans');await page.locator('#send-button').click();await page.waitForTimeout(4500);assert((await page.locator('#chat').innerText()).includes('Bonne réponse'));assert.equal(await page.evaluate(()=>NovaSave.exportData().variables.rep_t5_ch4_q1),'3 ans');
 await page.locator('#saved-toggle').click();assert(await page.locator('#saved-panel').isVisible());await page.reload();await page.waitForTimeout(9000);assert.equal(await page.evaluate(()=>NovaSave.exportData().variables.rep_t5_ch4_q1),'3 ans');
 await page.evaluate(()=>{const a=document.createElement('a');a.href='#'+btoa('SCR_REV_T4_CH03_ACT');document.querySelector('#chat').append(a);a.click();a.remove();});await page.waitForTimeout(4500);
 const frame=page.frameLocator('iframe[src*="activites-revision"]').last();await frame.locator('#questions').click();await page.waitForTimeout(3000);assert((await page.locator('#chat').innerText()).includes('Questions de connaissances'));
 await page.evaluate(()=>{const a=document.createElement('a');a.href='#'+btoa('SCR_QL_RESET');document.querySelector('#chat').append(a);a.click();a.remove();});await page.waitForTimeout(3500);
 for(const [question,keyboard] of [['Comment mieux mémoriser les dates ?',false],['Explique-moi le gouvernement',true]]){
  await page.locator('#user-input').fill(question);if(keyboard)await page.locator('#user-input').press('Enter');else await page.locator('#send-button').click();
  assert(await page.evaluate(()=>NovaQuestion.isPending()),'Chargement actif après envoi');assert(await page.locator('#question-loading').isVisible());await page.locator('#question-loading').screenshot({path:path.join(output,'attente.png')});
  try{await page.waitForFunction(()=>!NovaQuestion.isPending(),null,{timeout:25000});}catch(e){console.log(await page.locator('#chat').innerText());console.log('Errors',errors);await page.screenshot({path:path.join(output,'question-error.png')});throw e;}assert(!(await page.locator('#question-loading').isVisible()));
  console.log('Question terminée',question);const answer=page.locator('.bot-message').last();assert(await answer.locator('.nova-question-answer').count());assert((await answer.innerText()).includes('Poser une autre question'));assert(await answer.locator('a').count()>=2);
  if(!keyboard){await answer.getByRole('link',{name:/Poser une autre question/}).click({timeout:10000});await page.waitForTimeout(2500);}
 }
 console.log('Deux questions successives : attente active jusqu’aux suggestions, envoi bouton et clavier validés.');
 const sample=await page.evaluate(()=>{const x=NovaSave.exportData();x.history.bilan=[{date:'2026-10-07T07:00:00Z',score:15,max:25,variables:{parcoursExam:'CR',parcoursT1:1,parcoursT2:2,parcoursT3:3,parcoursT4:4,parcoursT5:5}}];x.history.entrainement=[{date:'2026-10-07T08:00:00Z',score:7,max:10,variables:{trainExam:'NAT',trainT4:7,trainTotal4:10}}];x.history.examen=[{date:'2026-10-07T09:00:00Z',score:33,max:40,variables:{lastExamCode:'CR_V01',lastKnowledge:23,lastSituations:10,lastT1:5,lastTotal1:8,lastT2:7,lastTotal2:8,lastT3:6,lastTotal3:8,lastT4:7,lastTotal4:8,lastT5:8,lastTotal5:8}}];return x;});await page.evaluate(x=>NovaSave.importData(x),sample);await page.locator('#saved-toggle').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export-pdf').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'mon-parcours-civique.pdf');await download.saveAs(path.join(output,'parcours.pdf'));assert(fs.statSync(path.join(output,'parcours.pdf')).size>10000);assert.equal(await page.locator('.nova-open-large').getAttribute('target'),'_blank');await page.locator('#saved-panel').screenshot({path:path.join(output,'export.png')});console.log('PDF téléchargé, export JSON conservé et ouverture en grand disponibles.');
 console.log('Chat intégré : 3 ans accepté, sauvegarde/rechargement et navigation depuis activité validés.');assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
