const {chromium}=require(process.env.NOVA_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
(async()=>{
 const base=path.resolve(__dirname,'..'),output=path.join(base,'.build_ui');fs.mkdirSync(output,{recursive:true});
 const data=JSON.parse(fs.readFileSync(base+'/activites-revision/data.json'));let origin;
 const server=http.createServer((req,res)=>{let p=path.join(base,decodeURIComponent(new URL(req.url,origin).pathname));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.md':'text/plain','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:740,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function open(k,st=0){await page.goto(origin+'/activites-revision/?chapitre='+k);await page.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);await page.evaluate(n=>{step=n;render();},st);assert(await page.locator('#questions').isEnabled());}



 await page.emulateMedia({reducedMotion:'reduce'});
 await page.route('**/chat_bot.md',r=>r.fulfill({body:fs.readFileSync(base+'/chat_bot.md','utf8').replaceAll('https://codeurfou-sys.github.io/chatbot_civique2/',origin+'/'),contentType:'text/plain'}));
 await page.goto(origin+'/chatbot/');await page.waitForFunction(()=>document.querySelector('#chat .messageOptions a'));await page.waitForFunction(()=>document.querySelector('#civicoach-loading').hidden);
 async function nav(id){await page.evaluate(id=>{const a=document.createElement('a');a.href='#'+btoa(id);document.querySelector('#chat').append(a);a.click();a.remove();},id);}
 async function correct(){await page.waitForFunction(()=>{const b=[...document.querySelectorAll('.bot-message')].at(-1);return b&&[...b.querySelectorAll('.messageOptions a')].some(a=>{try{return atob(a.hash.slice(1)).endsWith('_VRAI');}catch(e){return false;}});});const links=page.locator('.bot-message').last().locator('.messageOptions a');const data=await links.evaluateAll(as=>as.map(a=>({href:a.hash,text:a.textContent})));const picked=data.find(x=>{try{return atob(x.href.slice(1)).endsWith('_VRAI');}catch(e){return false;}});await page.locator('.bot-message').last().locator('a[href="'+picked.href+'"]').click();await page.waitForTimeout(15);const next=page.locator('.bot-message').last().getByRole('link',{name:/Question suivante|Voir mes résultats|Mes résultats|Continuer|Voir le résultat/}).first();await next.click({timeout:5000});return data.filter(x=>{try{return /_(VRAI|FAUX)$/.test(atob(x.href.slice(1)));}catch(e){return false;}});}
 for(let run=0;run<2;run++){await nav('SCR_ENT_CR_ALL_Q_LAUNCH_START');for(let i=0;i<10;i++)await correct();await page.waitForFunction(n=>NovaSave.exportData().history.entrainement.length>=n,run+1,{timeout:8000});console.log('Train',JSON.stringify(await page.evaluate(()=>NovaSave.exportData().history.entrainement.map(x=>[x.run,x.score,x.max]))));}

 const groups={};for(const key of Object.keys(await page.evaluate(()=>NovaSeries))){const group=key.replace(/_V\d+_(Q01|PART1)$/,'');(groups[group]||=[]).push(key);}
 const checked=await page.evaluate(groups=>{let count=0;for(const list of Object.values(groups)){const key=list[0].replace(/_V\d+_(Q01|PART1)$/,'');const remaining=NovaRandom.exportData().groups[key]?.remaining?.length||0;for(let i=0;i<remaining;i++)NovaRandom.select(list);const cycle=Array.from({length:10},()=>NovaRandom.select(list));if(new Set(cycle).size!==10)throw Error('Série répétée dans le cycle '+list[0]);if(NovaRandom.select(list)===cycle.at(-1))throw Error('Même série après le cycle');count++;}return count;},groups);assert.equal(checked,66);console.log('OK tirages : 63 familles d’entraînement + 3 examens, 10 séries sans répétition et transition suivante différente.');
 const checks=await page.evaluate(()=>{const ids=['ENT_CR_ALL_Q_V01_Q01','EXAM_CR_V01_Q01','BIL_ITEM_CR_001'];for(const id of ids){const source='<ul class="messageOptions">'+['Un','Deux','Trois','Quatre'].map((x,i)=>'<li><a href="#'+btoa(id+(i===2?'_VRAI':'_FAUX'))+'"><span class="qcm-letter">'+'ABCD'[i]+'</span> '+x+'</a></li>').join('')+'</ul>';let previous='';for(let i=0;i<30;i++){const t=document.createElement('template');t.innerHTML=NovaRandom.reorder(source);const choices=[...t.content.querySelectorAll('a')];const names=choices.map(a=>a.textContent.trim().slice(1).trim()).join('|');if(previous===names)throw Error('Même ordre');previous=names;if(choices.map(a=>a.querySelector('.qcm-letter').textContent).join('')!=='ABCD')throw Error('Lettres incohérentes');if(choices.find(a=>atob(a.hash.slice(1)).endsWith('_VRAI')).textContent.trim().slice(1).trim()!=='Trois')throw Error('Bonne réponse déplacée vers un mauvais lien');}}return 90;});assert.equal(checks,90);console.log('OK réponses : 90 mélanges successifs, lettres A–D cohérentes et bonne correction conservée.');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#chat .messageOptions a'));assert.equal(await page.evaluate(()=>NovaSave.exportData().history.entrainement.length),2);assert(Object.keys(await page.evaluate(()=>NovaRandom.exportData().groups)).length>=66);
 await nav('SCR_QL_RESET');await page.waitForFunction(()=>document.querySelector('.bot-message:last-of-type .nova-question-input'));await page.locator('#user-input').fill('Explique-moi le gouvernement');await page.locator('#send-button').click();await page.waitForFunction(()=>document.querySelector('.bot-message:last-of-type .nova-question-answer'));await page.locator('.bot-message').last().getByRole('link',{name:/Poser une autre question/}).click();await page.waitForFunction(()=>document.querySelector('.bot-message:last-of-type .nova-question-input'));const retry=await page.locator('.bot-message').last().innerText();assert(retry.includes('Écrivez votre question'));assert(!retry.includes('Par exemple'));assert(!retry.includes('Dans cette rubrique'));console.log('OK question suivante : consigne courte, sans exemples ni introduction.');
 await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#user-input').fill('Comment mieux mémoriser les dates ?');await page.locator('#send-button').click();assert(await page.locator('#question-loading').isVisible());assert((await page.locator('#question-loading').innerText()).includes('Réponse en cours de traitement'));await page.locator('#question-loading').screenshot({path:path.join(output,'attente-v22.png')});await page.waitForFunction(()=>!NovaQuestion.isPending(),null,{timeout:25000});console.log('OK points animés : indicateur visible jusqu’à la réponse et ses suggestions.');
 console.log('OK deux entraînements réellement terminés, sauvegarde et mémoire des tirages conservées après rechargement.');
 assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
