const fs=require('fs'),vm=require('vm'),assert=require('assert'),src=fs.readFileSync('chatbot/sauvegarde.js','utf8'),disk=new Map(),chapter='SCR_REV_T4_CH03';
function boot(){const handlers={},messages=[],source={postMessage:x=>messages.push(x)};const node=()=>({style:{},append(){},remove(){},replaceChildren(){},click(){this.clicked=true;},setAttribute(){}});const nodes={chat:node(),'save-status':node(),'saved-toggle':node(),'saved-panel':node(),export:node(),import:node(),erase:node()};const ctx={console,Date,JSON,URLSearchParams,setTimeout:f=>f(),location:{origin:'https://example.test',search:''},btoa:x=>Buffer.from(x).toString('base64'),localStorage:{getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v),removeItem:k=>disk.delete(k)},document:{getElementById:id=>nodes[id],querySelectorAll:()=>[{contentWindow:source,style:{},setAttribute(){}}],createElement:()=>node()},addEventListener:(k,f)=>handlers[k]=f};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(src,ctx);const vars={};ctx.NovaSave.before(vars);return{ctx,vars,source,handlers,messages};}
let {ctx,vars,source,handlers,messages}=boot();const emit=(payload,origin='https://example.test',sender=source)=>handlers.message({origin,source:sender,data:{source:'nova-activity',chapter,version:19,...payload}});
emit({complete:true},'https://evil.test');assert(!vars['activite_'+chapter]);emit({complete:true},undefined,{});assert(!vars['activite_'+chapter]);
const state={version:19,updated:Date.now(),step:1,score:3,total:4,reviewed:[0]};emit({activityState:JSON.stringify(state)});assert.equal(JSON.parse(vars['atelier_'+chapter]).step,1);emit({requestProgress:true});assert.equal(messages.at(-1).complete,false);assert(messages.at(-1).activityState);emit({complete:true});assert.equal(vars['activiteVersion_'+chapter],19);emit({reset:true});assert.equal(vars['activite_'+chapter],false);
// A standalone activity persists through the host and export/import.
disk.set('nova-ateliers-v19-'+chapter,JSON.stringify({...state,step:3,updated:Date.now()+100}));ctx.NovaSave.before(vars);ctx.NovaSave.after(vars);assert.equal(vars['activite_'+chapter],true);const exported=ctx.NovaSave.exportData();assert.equal(JSON.parse(exported.variables['atelier_'+chapter]).step,3);ctx.NovaSave.importData(exported);assert(!disk.has('nova-ateliers-v19-'+chapter));const reload=boot();assert.equal(reload.vars['activite_'+chapter],true);assert.equal(JSON.parse(reload.vars['atelier_'+chapter]).step,3);
console.log('OK v19 : messages vérifiés, état des ateliers, anciennes activités distinctes, reprise, export/import et ouverture en grand.');

// Compatible v18 workshops survive; the two changed chapters require the new exercise.
const oldKey='SCR_REV_T5_CH03';disk.set('nova-ateliers-v18-'+oldKey,JSON.stringify({version:18,step:2,complete:true,score:9,total:9,updated:Date.now()}));disk.set('nova-ateliers-v18-SCR_REV_T1_CH05',JSON.stringify({version:18,step:1,complete:true,score:4,total:4,updated:Date.now()}));const migrated=boot();assert.equal(JSON.parse(migrated.vars['atelier_'+oldKey]).version,19);assert(!migrated.vars['activite_SCR_REV_T1_CH05']);console.log('OK migration : résultats v18 compatibles conservés, nouveau chapitre langue non marqué terminé.');
