/* Parcours et événements, DOM simulé ; aucun contrôle visuel de navigateur. */
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const data=JSON.parse(fs.readFileSync('activites-revision/data.json')),regions=JSON.parse(fs.readFileSync('activites-revision/region-map.json')),source=fs.readFileSync('activites-revision/app.js','utf8');
class E{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.textContent='';this.handlers={};this.hidden=false;this.disabled=false;this.classes=new Set();this.classList={add:(...x)=>x.forEach(y=>this.classes.add(y)),remove:(...x)=>x.forEach(y=>this.classes.delete(y)),toggle:(x,v)=>v?this.classes.add(x):this.classes.delete(x)};this.contentWindow={};}append(...x){this.children.push(...x);}prepend(...x){this.children.unshift(...x);}replaceChildren(...x){this.children=x;}setAttribute(k,v){this[k]=v;}addEventListener(k,f){this.handlers[k]=f;}querySelectorAll(s){const all=this.children.flatMap(x=>[x,...x.querySelectorAll('*')]);if(s==='*')return all;if(['button','iframe','svg','canvas','img'].includes(s))return all.filter(x=>x.tagName.toLowerCase()===s);const m=s.match(/^\[data-([a-z]+)(?:="(.*?)")?\]$/);return m?all.filter(x=>x.dataset[m[1]]!==undefined&&(m[2]===undefined||String(x.dataset[m[1]])===m[2])):[];}querySelector(s){return this.querySelectorAll(s)[0]||null;}getBoundingClientRect(){return{left:0,top:0,width:600,height:450};}setPointerCapture(){}getContext(){return{fillRect(){},fillText(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},getImageData(){return{data:new Uint8Array(600*450*4)};}};}}
async function boot(chapter,saved=null){const n={};for(const id of ['activity','status','next','progress','s0','s1','s2','title','activity-title','instructions','restart','notions','questions','chapters','main-menu','correction','correction-button'])n['#'+id]=new E();const messages=[],handlers={},disk=new Map(saved?[['nova-ateliers-v16-'+chapter,JSON.stringify(saved)]]:[]);const c={document:{querySelector:s=>n[s],createElement:t=>new E(t),createElementNS:(ns,t)=>new E(t)},location:{search:'?chapitre='+chapter,origin:'https://codeurfou-sys.github.io'},URLSearchParams,localStorage:{getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v),removeItem:k=>disk.delete(k)},parent:{postMessage:x=>messages.push(x)},window:{addEventListener:(k,f)=>handlers[k]=f},fetch:async url=>({ok:true,json:async()=>url.startsWith('region-map')?regions:data}),console,setTimeout:f=>f()};vm.createContext(c);vm.runInContext(source,c);for(let i=0;i<15;i++)await Promise.resolve();return{c,n,messages,handlers,disk};}
function button(root,label){const b=root.querySelectorAll('button').find(x=>x.textContent===label);assert(b,'Bouton manquant : '+label);return b;}
(async()=>{let count=0;for(const [chapter,lesson]of Object.entries(data)){const {c,n,messages,handlers,disk}=await boot(chapter),root=n['#activity'];assert(!messages.some(x=>x.complete));assert(n['#questions'].disabled);assert(!lesson.quiz);for(let step=0;step<2;step++){const a=lesson.activities[step];n['#correction-button'].onclick();assert(!n['#correction'].hidden);assert(!messages.some(x=>x.complete));n['#correction-button'].onclick();assert(n['#correction'].hidden);
if(['cases','binary','phone','scratch'].includes(a.type)){for(const q of a.items){if(a.type==='phone'){for(const digit of q.answer)button(root,digit).onclick();button(root,'Valider').onclick();}else{if(a.type==='scratch'){root.querySelector('img').onload();const canvas=root.querySelector('canvas');canvas.handlers.pointerdown({pointerId:1,clientX:100,clientY:100});canvas.handlers.pointermove({clientX:200,clientY:100});canvas.handlers.pointerup();}const chosen=button(root,q.answer);chosen.onclick();const before=vm.runInContext('score',c);chosen.onclick();assert.equal(vm.runInContext('score',c),before);}assert(!n['#next'].hidden);n['#next'].onclick();}}
else if(['scheme','care','cycle'].includes(a.type)){button(root,a.items.find(x=>x.target==='2').label).onclick();assert(n['#next'].hidden);for(const x of a.items.slice().sort((x,y)=>Number(x.target)-Number(y.target)))button(root,x.label).onclick();assert(!n['#next'].hidden);n['#next'].onclick();}
else if(a.type==='memory'){const pairs=vm.runInContext('pairs',c);for(let id=0;id<a.pairs.length;id++)for(let i=0;i<pairs.length;i++)if(pairs[i].id===id)c.flip(i);assert(!n['#next'].hidden);n['#next'].onclick();}
else if(a.type==='geo'){const f=root.querySelector('iframe');handlers.message({origin:c.location.origin,source:f.contentWindow,data:{source:'nova-activity',complete:true,geoMode:'invalid'}});assert(n['#next'].hidden);handlers.message({origin:c.location.origin,source:f.contentWindow,data:{source:'nova-activity',complete:true,geoMode:a.mode}});assert(!n['#next'].hidden);n['#next'].onclick();}
else if(a.type==='payment'){for(const label of ['Carte Vitale · transmettre mes droits','Attestation de mutuelle · vérifier la part complémentaire','Carte bancaire · régler le reste'])button(root,label).onclick();button(root,'Parce que les organismes paient directement leurs parts dans cet exemple').onclick();assert(!n['#next'].hidden);n['#next'].onclick();}
else{for(let i=0;i<a.items.length;i++){c.setSelected(i);if(i===0){c.place(i,'__incorrect');assert(n['#next'].hidden);}const card=root.querySelector('[data-card="'+i+'"]'),dest=root.querySelector('[data-target="'+a.items[i].target+'"]');if(card.handlers.dragstart&&dest.handlers.drop){const transfer={setData(k,v){this.value=v;},getData(){return this.value;}};card.handlers.dragstart({dataTransfer:transfer});dest.handlers.drop({preventDefault(){},dataTransfer:transfer});}else{card.onclick();dest.onclick();}}assert(!n['#next'].hidden,chapter+' '+a.type+' step '+step+' placed '+vm.runInContext('placed.size',c));n['#next'].onclick();}count++;
if(step===0){assert(!messages.some(x=>x.complete));assert(n['#questions'].disabled);const saved=JSON.parse(disk.get('nova-ateliers-v16-'+chapter));assert.equal(saved.step,1);const reload=await boot(chapter,saved);assert.equal(vm.runInContext('step',reload.c),1);}}
assert(messages.some(x=>x.complete&&x.version===16));assert(!n['#questions'].disabled);for(const [id,target]of [['questions',chapter+'_VERIF'],['notions',chapter+'_GLO'],['chapters',chapter.replace(/_CH\d+$/,'_MENU')],['main-menu','MENU_PRINCIPAL']]){n['#'+id].onclick();assert.equal(messages.at(-1).navigate,target);}n['#restart'].onclick();assert(n['#questions'].disabled);assert.equal(vm.runInContext('step',c),0);assert(messages.some(x=>x.reset));}
assert.equal(count,38);console.log('OK v16 : 38 activités, 19 chapitres, clic/glisser/pointeur, corrections, garde des questions, retours, reprise et recommencer.');})().catch(e=>{console.error(e);process.exitCode=1;});
