const {chromium}=require(process.env.NOVA_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
(async()=>{
 const base=path.resolve(__dirname,'..'),output=path.join(base,'.build_ui');fs.mkdirSync(output,{recursive:true});
 const data=JSON.parse(fs.readFileSync(base+'/activites-revision/data.json'));let origin;
 const server=http.createServer((req,res)=>{let p=path.join(base,decodeURIComponent(new URL(req.url,origin).pathname.replace(/^\/chatbot_civique2/,'')));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.md':'text/plain','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:740,height:950},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function open(k,st=0){await page.goto(origin+'/activites-revision/?chapitre='+k);await page.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);await page.evaluate(n=>{step=n;render();},st);assert(await page.locator('#questions').isEnabled());}



 await page.emulateMedia({reducedMotion:'reduce'});
 await page.context().route('**/chat_bot.md*',r=>r.fulfill({body:fs.readFileSync(base+'/chat_bot.md','utf8').replaceAll('https://codeurfou-sys.github.io/chatbot_civique2/',origin+'/'),contentType:'text/plain'}));
 await page.goto(origin+'/chatbot/');await page.waitForFunction(()=>document.querySelector('#chat .messageOptions a'));await page.waitForFunction(()=>document.querySelector('#civicoach-loading').hidden);
 async function nav(id){await page.evaluate(id=>{const a=document.createElement('a');a.href='#'+btoa(id);document.querySelector('#chat').append(a);a.click();a.remove();},id);}
 async function correct(){await page.waitForFunction(()=>{const b=[...document.querySelectorAll('.bot-message')].at(-1);return b&&[...b.querySelectorAll('.messageOptions a')].some(a=>{try{return atob(a.hash.slice(1)).endsWith('_VRAI');}catch(e){return false;}});});const links=page.locator('.bot-message').last().locator('.messageOptions a');const data=await links.evaluateAll(as=>as.map(a=>({href:a.hash,text:a.textContent})));const picked=data.find(x=>{try{return atob(x.href.slice(1)).endsWith('_VRAI');}catch(e){return false;}});await page.locator('.bot-message').last().locator('a[href="'+picked.href+'"]').click();await page.waitForTimeout(15);const next=page.locator('.bot-message').last().getByRole('link',{name:/Question suivante|Voir mes résultats|Mes résultats|Continuer|Voir le résultat/}).first();await next.click({timeout:5000});return data.filter(x=>{try{return /_(VRAI|FAUX)$/.test(atob(x.href.slice(1)));}catch(e){return false;}});}

 const widget=fs.readFileSync(base+'/moodle/INTEGRATION_PIED_DE_PAGE.html','utf8').replaceAll('https://codeurfou-sys.github.io',origin);
 await page.route('**/moodle-test',r=>r.fulfill({contentType:'text/html',body:widget}));await page.goto(origin+'/moodle-test');await page.locator('#civi-launch').click();assert(await page.locator('#civi-wait').isVisible());await page.screenshot({path:path.join(output,'demarrage-moodle-v22.png')});await page.waitForFunction(()=>document.querySelector('#civi-wait').hidden,null,{timeout:30000});
 const frame=page.frames().find(f=>f.url().includes('/chatbot/'));assert(frame);await frame.waitForFunction(()=>typeof NovaSave!=='undefined');
 async function frameNav(id){await frame.evaluate(id=>{const a=document.createElement('a');a.href='#'+btoa(id);document.querySelector('#chat').append(a);a.click();a.remove();},id);}
 async function completeTraining(surface){await surface.evaluate(()=>{const a=document.createElement('a');a.href='#'+btoa('SCR_ENT_CR_ALL_Q_LAUNCH_START');document.querySelector('#chat').append(a);a.click();a.remove();});for(let i=0;i<10;i++){await surface.waitForFunction(()=>{const b=[...document.querySelectorAll('.bot-message')].at(-1);return b&&[...b.querySelectorAll('a')].some(a=>{try{return atob(a.hash.slice(1)).endsWith('_VRAI');}catch(e){return false;}});},null,{timeout:10000});const href=await surface.locator('.bot-message').last().locator('a').evaluateAll(as=>as.find(a=>{try{return atob(a.hash.slice(1)).endsWith('_VRAI');}catch(e){return false;}}).getAttribute('href'));await surface.locator('.bot-message').last().locator('a[href="'+href+'"]').click();await surface.locator('.bot-message').last().getByRole('link',{name:/Question suivante|Voir mes résultats/}).click();}}
 await completeTraining(frame);await frame.waitForFunction(()=>NovaSave.exportData().history.entrainement.length===1);
 await page.context().addInitScript(()=>{if(location.search.includes('vue=resultats'))localStorage.removeItem('novafrate-civique-v14');});await frameNav('SCR_SAVE_MENU');
 async function resultsFrom(surface){const promise=page.waitForEvent('popup');await surface.locator('.nova-open-saved').last().click();const popup=await promise;await popup.waitForFunction(()=>document.querySelector('#saved-list')?.textContent.includes('10/10'),null,{timeout:15000});return popup;}
 const results=await resultsFrom(frame);assert.equal(await results.evaluate(()=>NovaSave.exportData().history.entrainement.length),1);assert(await results.locator('#export').isHidden());assert(await results.locator('#import').isHidden());assert(await results.locator('#return-moodle').isEnabled());
 const dlPromise=results.waitForEvent('download');await results.locator('#export-pdf').click();const dl=await dlPromise;await dl.saveAs(path.join(output,'parcours-v22.pdf'));await results.screenshot({path:path.join(output,'resultats-v22.png')});
 const closed=results.waitForEvent('close');await results.locator('#return-moodle').click();await closed;assert.equal(await frame.evaluate(()=>NovaSave.exportData().history.entrainement.length),1);
 const full=await resultsFrom(frame);await full.locator('#return-full').click();await full.waitForFunction(()=>typeof NovaSave!=='undefined'&&NovaSave.exportData().history.entrainement.length===1);await full.waitForFunction(()=>[...document.querySelectorAll('.bot-message')].at(-1)?.textContent.includes('Ouvrir mes résultats sauvegardés'),null,{timeout:15000});await completeTraining(full);await full.waitForFunction(()=>NovaSave.exportData().history.entrainement.length===2);await frame.waitForFunction(()=>NovaSave.exportData().history.entrainement.length===2);
 await full.evaluate(()=>{const a=document.createElement('a');a.href='#'+btoa('SCR_SAVE_MENU');document.querySelector('#chat').append(a);a.click();a.remove();});const popupPromise=full.waitForEvent('popup');await full.locator('.nova-open-saved').last().click();const latest=await popupPromise;await latest.waitForFunction(()=>typeof NovaSave!=='undefined'&&NovaSave.exportData().history.entrainement.length===2);const closedAgain=latest.waitForEvent('close');await latest.locator('#return-moodle').click();await closedAgain;await frame.waitForFunction(()=>NovaSave.exportData().history.entrainement.length===2);
 await page.locator('#civi-close').click();await page.locator('#civi-launch').click();assert(await page.locator('#civi-wait').isHidden());assert.equal(await frame.evaluate(()=>NovaSave.exportData().history.entrainement.length),2);
 await page.reload();await page.locator('#civi-launch').click();await page.waitForFunction(()=>document.querySelector('#civi-wait').hidden,null,{timeout:30000});const resumed=page.frames().find(f=>f.url().includes('/chatbot/'));assert.equal(await resumed.evaluate(()=>NovaSave.exportData().history.entrainement.length),2);
 console.log('Moodle et deux entraînements terminés ; test reset.');
 const activePromise=page.waitForEvent("popup");await resumed.evaluate(()=>NovaLink.open("./?reprendre=1"));const active=await activePromise;await active.waitForFunction(()=>typeof NovaSave!=="undefined"&&NovaSave.exportData().history.entrainement.length===2);
 const stale=await active.evaluate(()=>NovaSave.exportData());
 const erasePromise=page.waitForEvent("popup");await resumed.evaluate(()=>NovaLink.open("./?vue=resultats"));const eraseView=await erasePromise;await eraseView.waitForFunction(()=>typeof NovaSave!=="undefined"&&NovaSave.exportData().history.entrainement.length===2);await eraseView.evaluate(()=>{const disk=new Map([['novafrate-civique-v14',JSON.stringify(NovaSave.exportData())]]);Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,String(v)),removeItem:k=>disk.delete(k),key:i=>[...disk.keys()][i]||null,get length(){return disk.size;}}});});await eraseView.locator('#erase').click();await eraseView.getByRole('button',{name:'Annuler',exact:true}).click();assert.equal(await active.evaluate(()=>NovaSave.exportData().history.entrainement.length),2);
 await eraseView.locator('#erase').click();await eraseView.getByRole('button',{name:'Oui, effacer ma progression',exact:true}).click();
 for(const surface of [active,resumed])await surface.waitForFunction(()=>NovaSave.exportData().resetAt>0&&Object.values(NovaSave.exportData().history).every(rows=>rows.length===0),null,{polling:100});
 await active.evaluate(old=>NovaSave.mergeData(old),stale);assert.equal(await active.evaluate(()=>NovaSave.exportData().history.entrainement.length),0);
 await completeTraining(active);await active.waitForFunction(()=>NovaSave.exportData().history.entrainement.length===1);await resumed.waitForFunction(()=>NovaSave.exportData().history.entrainement.length===1,null,{polling:100});
 await active.reload();await active.waitForFunction(()=>typeof NovaSave!=='undefined');assert.equal(await active.evaluate(()=>NovaSave.exportData().history.entrainement.length),1);
 console.log('OK effacement : annulation, confirmation intégrée, synchronisation Moodle/plein écran, rejet ancien état, nouvelle tentative après reset et rechargement.');
 console.log('OK Moodle : attente avec mascotte, entraînement réellement enregistré, transfert vers résultats même sans stockage préalable, PDF seul, retours NovaFrate et plein écran, deux résultats synchronisés et repris après rechargement.');
 assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
