'use strict';
const NS='http://www.w3.org/2000/svg';let completed={fleuves:false,massifs:false};try{completed=JSON.parse(localStorage.getItem('nova-geo-completed'))||completed;}catch(e){}
function notifyCompleted(){if(scoped==='fleuves'||scoped==='massifs')return;if(completed.fleuves&&completed.massifs){try{localStorage.setItem('nova-activity-SCR_REV_T4_CH02','true');}catch(e){}parent.postMessage({source:'nova-activity',chapter:'SCR_REV_T4_CH02',complete:true},location.origin);}}
const scoped=new URLSearchParams(location.search).get('mode');let data,mode='fleuves',index=0,score=0,attempted=false;
const map=document.querySelector('#map'),statusBox=document.querySelector('#status');
const details={'Seine':'La Seine traverse Paris et rejoint la Manche.','Loire':'La Loire rejoint l’océan Atlantique près de Saint-Nazaire.','Garonne':'La Garonne passe par Toulouse et Bordeaux ; avec la Dordogne, elle forme l’estuaire de la Gironde.','Rhône':'Le Rhône traverse Lyon et rejoint la mer Méditerranée.','Rhin':'Le Rhin longe une partie de la frontière à l’est de la France et rejoint la mer du Nord.','Alpes':'Les Alpes se trouvent au sud-est, à proximité de la Suisse et de l’Italie.','Pyrénées':'Les Pyrénées marquent la frontière avec l’Espagne.','Massif central':'Le Massif central occupe le centre-sud de la France.','Jura':'Le Jura se situe à l’est, près de la Suisse et au nord des Alpes.','Vosges':'Les Vosges se trouvent dans le nord-est, à l’ouest du Rhin.'};
function svg(tag,attrs){const node=document.createElementNS(NS,tag);for(const [key,val] of Object.entries(attrs))node.setAttribute(key,val);return node}
function update(){const list=data[mode];document.querySelector('#progress').value=index;document.querySelector('#next').hidden=mode!=='fleuves'||index<list.length;
 document.querySelector('#prompt').textContent=index<list.length?`Repère ${index+1}/5 : cliquez sur ${list[index].name}`:`Activité terminée — votre score : ${score}/5`;
 if(index===list.length){if(scoped===mode)parent.postMessage({source:'nova-activity',chapter:'SCR_REV_T4_CH02',complete:true,geoMode:mode,score,total:5},location.origin);completed[mode]=true;try{localStorage.setItem('nova-geo-completed',JSON.stringify(completed));}catch(e){}notifyCompleted();} if(index===list.length)statusBox.textContent=`Vous avez retrouvé les cinq repères. ${score===5?'Félicitations !':'Relisez les indications, puis recommencez pour confirmer vos repères.'}`;
}
function select(name){const list=data[mode];if(index>=list.length)return;const target=list[index];
 if(name!==target.name){attempted=true;statusBox.textContent=`Ce n’est pas ${target.name}. ${details[target.name]} Essayez une autre zone.`;return}
 if(!attempted)score++;const path=map.querySelector('[data-name="'+name+'"]');path.classList.add('done');const text=svg('text',{x:target.x,y:target.y,'text-anchor':'middle'});text.textContent=target.name;map.append(text);statusBox.textContent='Bonne réponse. '+details[target.name];index++;attempted=false;update();
}
function start(newMode){if(!data)return;mode=newMode;index=0;score=0;attempted=false;map.replaceChildren();document.querySelector('#rivers').classList.toggle('active',mode==='fleuves');document.querySelector('#mountains').classList.toggle('active',mode==='massifs');
 map.append(svg('path',{d:data.outline,fill:'#fffaf2',stroke:'#606b76','stroke-width':1.5}));data[mode].forEach((item,i)=>{const p=svg('path',{d:item.path,fill:mode==='fleuves'?'none':'#be8a54',stroke:mode==='fleuves'?'#177fa9':'#915f2f','stroke-width':mode==='fleuves'?5:2,tabindex:0,role:'button','aria-label':`Zone ${i+1}`,'data-name':item.name,class:'zone','pointer-events':mode==='fleuves'?'stroke':'all'});p.addEventListener('click',()=>select(item.name));p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(item.name)}});map.append(p)});statusBox.textContent='Choisissez le repère demandé. Une indication vous aidera si vous vous trompez.';update();describeMap();}
document.querySelector('#rivers').onclick=()=>start('fleuves');document.querySelector('#mountains').onclick=()=>start('massifs');document.querySelector('#restart').onclick=()=>start(mode);document.querySelector('#next').onclick=()=>start('massifs');
fetch('data.json').then(r=>{if(!r.ok)throw Error('Carte indisponible');return r.json()}).then(d=>{data=d;if(scoped==='fleuves'||scoped==='massifs'){document.querySelector('#rivers').hidden=true;document.querySelector('#mountains').hidden=true;document.querySelector('#next').style.display='none';start(scoped);}else{start('fleuves');notifyCompleted();}}).catch(()=>{statusBox.textContent='La carte n’a pas pu être chargée. Actualisez la page ou revenez au cours.'});

document.getElementById('return-chat').onclick=()=>{if(parent!==window)parent.postMessage({source:'nova-activity',chapter:'SCR_REV_T4_CH02',navigate:'MENU_PRINCIPAL'},location.origin);else location.href=new URL('../chatbot/?retour=MENU_PRINCIPAL',location.href).href;};

const descriptions={Seine:'Zone : au nord. Le cours d’eau vient de l’est de la carte, traverse le bassin parisien et se dirige vers le nord-ouest jusqu’à la Manche.',Loire:'Zone : au centre. Le cours d’eau descend du centre-sud, remonte vers le nord puis forme un large coude vers l’ouest, jusqu’à l’Atlantique.',Garonne:'Zone : au sud-ouest. Le cours d’eau vient de la frontière espagnole, traverse la plaine du sud-ouest et se dirige vers l’estuaire sur la côte atlantique.',Rhône:'Zone : à l’est et au sud-est. Le cours d’eau arrive par l’est, descend le long d’une vallée orientée nord-sud et rejoint la Méditerranée.',Rhin:'Zone : à l’extrême est. Le cours d’eau suit une partie de la frontière orientale et poursuit sa route vers le nord, au-delà de la carte.',Alpes:'Zone montagneuse au sud-est, près des frontières suisse et italienne.',Pyrénées:'Zone montagneuse au sud-ouest, le long de la frontière espagnole.',
'Massif central':'Zone montagneuse dans le centre-sud, à l’intérieur des terres.',Jura:'Zone montagneuse à l’est, près de la Suisse, au nord des Alpes.',Vosges:'Zone montagneuse au nord-est, à l’ouest de la frontière orientale.'};
function describeMap(){if(!data)return;const accessible=!!(window.NovaAccess?.settings().audio||window.NovaAccess?.settings().hover);let list=document.getElementById('map-description');if(!list){list=document.createElement('section');list.id='map-description';list.className='civi-access-description';map.before(list);}list.hidden=!accessible;list.replaceChildren();const intro=document.createElement('p');intro.textContent='La carte représente la France métropolitaine. Le nord est en haut, l’ouest à gauche et l’est à droite. La Manche se situe au nord-ouest, l’Atlantique à l’ouest et la Méditerranée au sud-est. Choisissez la zone qui correspond au repère demandé.';list.append(intro);data[mode].forEach((item,i)=>{const desc=descriptions[item.name];const path=map.querySelector('[data-name="'+item.name+'"]');if(path){path.setAttribute('aria-label','Zone '+(i+1)+' : '+desc);path.dataset.audioDescription='Zone '+(i+1)+' : '+desc;}const button=document.createElement('button');button.type='button';button.textContent='Zone '+(i+1)+' — '+desc;button.onclick=()=>select(item.name);list.append(button);});}
window.addEventListener('civicoach-accessibility-change',describeMap);
