'use strict';
const NS='http://www.w3.org/2000/svg';
const map=document.querySelector('#map'),promptBox=document.querySelector('#prompt'),statusBox=document.querySelector('#status'),next=document.querySelector('#next'),restart=document.querySelector('#restart'),progress=document.querySelector('#progress');
const details={'Seine':'La Seine traverse Paris et rejoint la Manche.','Loire':'La Loire rejoint l’océan Atlantique près de Saint-Nazaire.','Garonne':'La Garonne passe par Toulouse et Bordeaux, dans le sud-ouest.','Rhône':'Le Rhône traverse Lyon et rejoint la mer Méditerranée, dans le sud-est.','Rhin':'Le Rhin longe une partie de la frontière à l’est de la France.','Alpes':'Les Alpes se trouvent au sud-est, près de la Suisse et de l’Italie.','Pyrénées':'Les Pyrénées marquent la frontière avec l’Espagne, au sud-ouest.','Massif central':'Le Massif central occupe le centre-sud de la France.','Jura':'Le Jura se situe à l’est, près de la Suisse et au nord des Alpes.','Vosges':'Les Vosges se trouvent dans le nord-est, à l’ouest du Rhin.'};
let data,questions=[],index=0,score=0,answered=false,previous='';
function svg(tag,attrs){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n}
function draw(){answered=false;next.hidden=true;restart.hidden=true;map.replaceChildren();const q=questions[index];promptBox.textContent=`Question ${index+1}/2 — Où se ${q.mode==='fleuves'?'situe le fleuve':'trouve le massif'} ${q.name} ?`;statusBox.textContent='Choisissez la zone correspondant au repère demandé. Les zones sont numérotées pour permettre la navigation au clavier.';map.append(svg('path',{d:data.outline,fill:'#fffaf2',stroke:'#606b76','stroke-width':1.5}));
data[q.mode].forEach((item,i)=>{const p=svg('path',{d:item.path,fill:q.mode==='fleuves'?'none':'#be8a54',stroke:q.mode==='fleuves'?'#177fa9':'#915f2f','stroke-width':q.mode==='fleuves'?5:2,tabindex:0,role:'button','aria-label':`Zone ${i+1}`,'data-name':item.name,class:'zone','pointer-events':q.mode==='fleuves'?'stroke':'all'});p.addEventListener('click',()=>answer(item.name));p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();answer(item.name)}});map.append(p)})}
function answer(name){if(answered)return;answered=true;const q=questions[index],correct=name===q.name;if(correct)score++;map.querySelector('[data-name="'+q.name+'"]').classList.add('correct');if(!correct)map.querySelector('[data-name="'+name+'"]').classList.add('wrong');
for(const p of map.querySelectorAll('.zone')){p.setAttribute('aria-disabled','true');p.setAttribute('tabindex','-1')}
progress.value=index+1;statusBox.textContent=(correct?'✅ Bonne réponse ! ':'🌱 Vous avez choisi '+name+'. La réponse attendue est '+q.name+'. ')+details[q.name]+' Pour retenir ce repère, associez son nom à sa position et à une ville ou une frontière.';next.hidden=false;next.textContent=index===0?'➡️ Question suivante':'📊 Voir mes résultats';next.focus()}
function start(){if(!data)return;index=0;score=0;progress.value=0;let r;do{r=Math.floor(Math.random()*5)}while(String(r)===previous);previous=String(r);const m=Math.floor(Math.random()*5);questions=[{mode:'fleuves',name:data.fleuves[r].name},{mode:'massifs',name:data.massifs[m].name}];draw()}
next.onclick=()=>{if(!answered)return;if(index===0){index=1;draw()}else{promptBox.textContent=`Votre résultat : ${score}/2 — ${score*50} %`;statusBox.textContent=score===2?'Félicitations ! Vous avez identifié les deux repères. Confirmez ces acquis avec deux nouvelles questions.':score===1?'Vous avez identifié un repère sur deux. Retrouvez sur la carte celui qui vous a manqué, reformulez l’indication géographique puis essayez deux nouvelles questions.':'Ces deux repères sont à revoir. Relisez les corrections, associez chaque nom à sa position puis refaites l’activité. Vous progresserez en revenant régulièrement sur la carte.';map.replaceChildren();next.hidden=true;restart.hidden=false;restart.focus()}};
restart.onclick=start;
fetch('data.json').then(r=>{if(!r.ok)throw Error('Carte indisponible');return r.json()}).then(d=>{data=d;start()}).catch(()=>{promptBox.textContent='Carte indisponible';statusBox.textContent='Actualisez la page ou revenez au cours de géographie.'});
