'use strict';
const chapter=new URLSearchParams(location.search).get('chapitre');
const root=document.querySelector('#activity'),statusBox=document.querySelector('#status'),next=document.querySelector('#next');
const KEY='nova-ateliers-v16-'+chapter,NS='http://www.w3.org/2000/svg';
let lesson,regions=[],step=0,selected=null,placed=new Set(),pairs=[],flipped=[],matched=new Set(),locked=false,qi=0,answered=false,score=0,total=0,stageReady=false,generation=0,reviewed=[],counters={},paymentStep=0,checkpointScore=0,checkpointTotal=0;
const shuffle=arr=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function svg(tag,attrs){const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function message(text,ok=false){statusBox.textContent=text;statusBox.className=ok?'success':'hint';}
function send(payload){if(parent!==window)parent.postMessage({source:'nova-activity',chapter,version:16,...payload},location.origin);}
function snapshot(){return {version:16,updated:Date.now(),step,score:checkpointScore,total:checkpointTotal,reviewed,complete:step===2};}
function store(){const state=snapshot();try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}send({activityState:JSON.stringify(state)});}
function navigation(target){if(parent!==window){send({navigate:target});message('Retour au chatbot…');}else location.href='../chatbot/?retour='+encodeURIComponent(target);}
function complete(){store();send({complete:true});}
function update(){document.querySelector('#progress').value=step;for(let i=0;i<3;i++)document.querySelector('#s'+i).className=i<step?'complete':i===step?'active':'';document.querySelector('#questions').disabled=step<2;}
function finish(explanation){stageReady=true;message(explanation||'Activité terminée. Consultez le corrigé pour comprendre chaque réponse.',true);next.hidden=false;next.textContent=step===0?'② Passer à la deuxième activité':'✓ Terminer les activités';}
function firstTry(id,ok){if(counters[id])return;counters[id]=true;total++;if(ok)score++;}
function setSelected(i){selected=i;root.querySelectorAll('[data-card]').forEach(b=>{const yes=Number(b.dataset.card)===i;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});message('Élément sélectionné : choisissez sa destination.');}
function place(i,target){if(stageReady||i===null||placed.has(i))return;const a=lesson.activities[step];if(!Number.isInteger(i)||i<0||i>=a.items.length)return;const item=a.items[i],ok=item.target===target;firstTry('p'+i,ok);if(!ok){message('Cette destination ne correspond pas. Relisez la situation ou consultez le corrigé pour comprendre la distinction.');return;}placed.add(i);const dest=[...root.querySelectorAll('[data-target]')].find(b=>b.dataset.target===target);if(a.type==='flag'&&dest)dest.style.background={Bleu:'#0055a4',Blanc:'#fff',Rouge:'#ef4135'}[item.label];if(dest&&dest.tagName.toLowerCase()!=='path')dest.append(element('span',item.label,'placed'));else if(dest){dest.classList.add('done');const r=regions.find(x=>x.code===target);if(r){const t=svg('text',{x:r.x,y:r.y,'text-anchor':'middle','pointer-events':'none'});t.textContent=a.revealNames?'✓':item.label;root.querySelector('svg').append(t);}}
 const card=root.querySelector('[data-card="'+i+'"]');card.classList.remove('selected');card.classList.add('done');card.disabled=true;card.draggable=false;selected=null;message('Bonne association. '+item.explanation,true);if(placed.size===a.items.length)finish();}
function cardList(a){const cards=element('div',undefined,'cards');shuffle(a.items.map((item,i)=>({item,i}))).forEach(({item,i})=>{const b=element('button',item.label,'card');b.dataset.card=i;b.draggable=true;b.onclick=()=>setSelected(i);b.addEventListener('dragstart',e=>{selected=i;e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move';});if(a.type==='flag'){const dot=element('span',undefined,'swatch');dot.style.background={Bleu:'#0055a4',Blanc:'#fff',Rouge:'#ef4135'}[item.label];b.prepend(dot);}cards.append(b);});root.append(cards);}
function destinationEvents(b,target){b.dataset.target=target;b.onclick=()=>place(selected,target);b.addEventListener('dragover',e=>{e.preventDefault();b.classList.add('drag-over');});b.addEventListener('dragleave',()=>b.classList.remove('drag-over'));b.addEventListener('drop',e=>{e.preventDefault();b.classList.remove('drag-over');const raw=e.dataTransfer.getData('text/plain');if(/^\d+$/.test(raw))place(Number(raw),target);});}
function building(label){const s=svg('svg',{viewBox:'0 0 180 95','aria-hidden':'true',class:'building'});s.append(svg('path',{d:'M15 40 L90 8 L165 40 Z',fill:'#a84363'}),svg('rect',{x:25,y:40,width:130,height:48,rx:3,fill:'#f4d395'}),svg('rect',{x:78,y:60,width:24,height:28,fill:'#765974'}));for(const x of [40,60,108,128])s.append(svg('rect',{x,y:50,width:12,height:14,fill:'#6ba7c5'}));return s;}
function placement(a){if(a.context)root.append(element('p',a.context,'scenario'));cardList(a);const groups=a.groups||a.items.map(x=>x.target);const ordered=['sort','timeline','flag','order','school','payslip'].includes(a.type);const targets=ordered?[...new Set(groups)]:shuffle([...new Set(groups)]);const board=element('div',undefined,a.type==='flag'?'flag':a.type==='timeline'?'destinations timeline':a.type==='payslip'?'destinations payslip':'destinations');targets.forEach((target,i)=>{const text=a.type==='flag'?['Bande gauche','Bande centrale','Bande droite'][i]:a.type==='order'?'Position '+target:target;const b=element('button',text,'destination');if(a.type==='school')b.prepend(building(target));destinationEvents(b,target);b.setAttribute('aria-label','Destination : '+text);board.append(b);});root.append(board);}
function connect(a){let left=null;const board=element('div',undefined,'connections'),l=element('div',undefined,'connection-col'),r=element('div',undefined,'connection-col');shuffle(a.items.map((x,i)=>({x,i}))).forEach(({x,i})=>{const b=element('button',x.label,'card');b.dataset.card=i;b.onclick=()=>{left=i;setSelected(i);};l.append(b);});shuffle(a.items).forEach(x=>{const b=element('button',x.target,'destination');b.dataset.target=x.target;b.onclick=()=>place(left,x.target);r.append(b);});board.append(l,r);root.append(board);}
function careIcon(i){const s=svg('svg',{viewBox:'0 0 120 100',class:'care-icon','aria-hidden':'true'});s.append(svg('rect',{x:4,y:4,width:112,height:92,rx:20,fill:['#dbe8f5','#e0eee7','#f7e3bd','#e9dff0','#f8dfe5','#d9edf1'][i]}));if(i===5){s.append(svg('circle',{cx:60,cy:40,r:24,fill:'#e4ad82'}),svg('circle',{cx:51,cy:34,r:2,fill:'#263445'}),svg('circle',{cx:69,cy:34,r:2,fill:'#263445'}),svg('rect',{x:37,y:42,width:46,height:22,rx:8,fill:'#fff'}),svg('path',{d:'M28 90 Q60 60 92 90',stroke:'#628aab','stroke-width':15,fill:'none'}));}else if(i===0){s.append(svg('rect',{x:39,y:18,width:42,height:64,rx:8,fill:'#354657'}),svg('rect',{x:45,y:25,width:30,height:43,rx:3,fill:'#fff'}),svg('circle',{cx:60,cy:75,r:3,fill:'#fff'}));}else if(i===1){s.append(svg('path',{d:'M35 20 V45 Q35 68 60 68 Q85 68 85 45 V20 M60 68 V80 H89',fill:'none',stroke:'#476681','stroke-width':6}),svg('circle',{cx:94,cy:80,r:7,fill:'#a84363'}));}else if(i===2){s.append(svg('rect',{x:30,y:15,width:60,height:72,rx:6,fill:'#fff'}));for(let y=32;y<72;y+=13)s.append(svg('path',{d:'M40 '+y+' H78',stroke:'#628aab','stroke-width':4}));}else if(i===3){s.append(svg('path',{d:'M50 20 H70 V40 H90 V60 H70 V80 H50 V60 H30 V40 H50 Z',fill:'#4e9674'}));}else{s.append(svg('circle',{cx:54,cy:43,r:22,fill:'#fff',stroke:'#628aab','stroke-width':6}),svg('path',{d:'M70 61 L91 83',stroke:'#628aab','stroke-width':10}));}return s;}
function scheme(a){const track=element('div',undefined,a.type==='cycle'?'scheme-track cycle-track':'scheme-track'),choices=element('div',undefined,'cards');root.append(track,choices);let pos=0;shuffle(a.items.map((x,i)=>({x,i}))).forEach(({x,i})=>{const b=element('button',x.label,'card');if(a.type==='care')b.prepend(careIcon(i));b.onclick=()=>{if(stageReady||b.disabled)return;const ok=x.target===String(pos+1);firstTry('s'+pos,ok);if(!ok){message('Cette étape vient à un autre moment. Recherchez celle qui précède dans ce parcours.');return;}b.disabled=true;b.classList.add('done');const node=element('div',undefined,'scheme-node');node.append(element('strong',String(++pos)),element('span',x.label));track.append(node);message(x.explanation,true);if(pos===a.items.length){if(a.type==='cycle')track.append(element('p','↻ Après usage : trier à nouveau, réduire et réemployer.','loop'));finish();}};choices.append(b);});if(a.type==='care')root.prepend(careIcon(5),element('p','😷 Je suis malade, sans signe d’urgence : choisissez les étapes dans l’ordre. Si la situation est urgente, ce parcours ne s’applique pas.','scenario'));}
function flip(i){if(locked||matched.has(pairs[i].id)||flipped.includes(i)||stageReady)return;const b=root.querySelector('[data-memory="'+i+'"]');b.textContent=pairs[i].text;b.classList.add('flipped');flipped.push(i);if(flipped.length<2)return;const [a,c]=flipped;if(pairs[a].id===pairs[c].id){matched.add(pairs[a].id);flipped=[];root.querySelectorAll('[data-memory]').forEach((b,j)=>{if(matched.has(pairs[j].id)){b.disabled=true;b.classList.add('done');}});message('Bonne paire : '+lesson.activities[step].pairs[pairs[a].id].join(' — '),true);if(matched.size===lesson.activities[step].pairs.length)finish();}else{locked=true;message('Ces cartes ne forment pas une paire. Mémorisez-les, puis réessayez.');const g=generation;setTimeout(()=>{if(g!==generation)return;for(const j of flipped){const b=root.querySelector('[data-memory="'+j+'"]');if(b){b.textContent='Retourner la carte';b.classList.remove('flipped');}}flipped=[];locked=false;},1100);}}
function memory(a){pairs=shuffle(a.pairs.flatMap((p,id)=>p.map(text=>({id,text}))));const grid=element('div',undefined,'memory');pairs.forEach((p,i)=>{const b=element('button','Retourner la carte');b.dataset.memory=i;b.onclick=()=>flip(i);grid.append(b);});root.append(grid);}
function answerCase(a,choice,list){if(answered)return;answered=true;const q=a.items[qi],ok=choice===q.answer||(q.accepted||[]).includes(choice);firstTry('q'+qi,ok);if(list)list.querySelectorAll('button').forEach(x=>{x.disabled=true;if(x.textContent===q.answer)x.classList.add('correct');});message((ok?'Bonne réponse. ':'À retenir : '+q.answer+'. ')+q.explanation,ok);next.hidden=false;next.textContent=qi===a.items.length-1?'Terminer cette activité':'Situation suivante';}
function cases(a){root.replaceChildren();answered=false;const q=a.items[qi];root.append(element('p','Situation '+(qi+1)+'/'+a.items.length,'counter'),element('h3',q.prompt,'scenario'));if(a.type==='scratch'){scratch(q);}
 else if(a.type==='phone'){const phone=element('div',undefined,'phone'),display=element('output','','phone-display'),keys=element('div',undefined,'keypad');let digits='';display.setAttribute('aria-label','Numéro composé');phone.append(element('p','Téléphone d’entraînement · aucun appel réel'),display,keys);for(const n of ['1','2','3','4','5','6','7','8','9','⌫','0','Valider']){const b=element('button',n);b.onclick=()=>{if(answered)return;if(n==='⌫')digits=digits.slice(0,-1);else if(n==='Valider'){if(!digits){message('Composez un numéro avant de valider.');return;}answerCase(a,digits,keys);}else if(digits.length<3)digits+=n;display.textContent=digits;};keys.append(b);}root.append(phone);}
 else {const list=element('div',undefined,a.type==='binary'?'binary-options':'quiz-options');shuffle(q.options).forEach(choice=>{const b=element('button',choice);b.onclick=()=>{answerCase(a,choice,list);if(choice!==q.answer)b.classList.add('wrong');};list.append(b);});root.append(list);}}
function scratch(q){const wrap=element('div',undefined,'scratch-wrap'),img=element('img'),canvas=element('canvas');img.src=q.image;img.alt='Œuvre à découvrir';wrap.append(img,canvas);root.append(wrap);const tools=element('div',undefined,'scratch-tools'),reveal=element('button','Découvrir sans gratter (clavier)'),list=element('div',undefined,'quiz-options');list.hidden=true;let ctx,active=false,last=null,opened=false;const g=generation;
 function unlock(){if(opened)return;opened=true;canvas.hidden=true;list.hidden=false;img.alt=q.work;message('Observez l’œuvre, puis choisissez l’artiste.');}
 img.onload=()=>{if(g!==generation)return;canvas.width=600;canvas.height=450;ctx=canvas.getContext('2d');ctx.fillStyle='#a84363';ctx.fillRect(0,0,600,450);ctx.fillStyle='#fff';ctx.font='25px sans-serif';ctx.textAlign='center';ctx.fillText('Grattez pour découvrir',300,220);};img.onerror=()=>{if(g!==generation)return;message('L’image ne peut pas être affichée. Consultez le corrigé ou revenez au cours.');};
 function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*600/r.width,(e.clientY-r.top)*450/r.height];}
 function clear(e){if(!ctx||!active||opened)return;const p=point(e);ctx.globalCompositeOperation='destination-out';ctx.lineWidth=62;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(...(last||p));ctx.lineTo(...p);ctx.stroke();last=p;}
 canvas.addEventListener('pointerdown',e=>{active=true;last=point(e);canvas.setPointerCapture(e.pointerId);clear(e);});canvas.addEventListener('pointermove',clear);canvas.addEventListener('pointerup',()=>{active=false;last=null;if(!ctx)return;const pixels=ctx.getImageData(0,0,600,450).data;let cleared=0,n=0;for(let i=3;i<pixels.length;i+=256){n++;if(pixels[i]<100)cleared++;}if(cleared/n>.45)unlock();});canvas.addEventListener('pointercancel',()=>{active=false;last=null;});reveal.onclick=unlock;tools.append(reveal);root.append(tools);shuffle(q.options).forEach(choice=>{const b=element('button',choice);b.onclick=()=>answerCase(lesson.activities[step],choice,list);list.append(b);});root.append(list);}
function mapActivity(a){cardList(a);const board=element('div',undefined,'map-board'),map=svg('svg',{viewBox:'0 0 730 640',class:'region-map',role:'group','aria-label':'Carte des régions métropolitaines'});regions.filter(r=>!r.overseas).forEach((r,i)=>{const p=svg('path',{d:r.path,fill:['#f5d7a3','#d5e9e3','#e6d7ed','#d7e7f5'][i%4],stroke:'#fff','stroke-width':2,tabindex:0,role:'button','aria-label':a.revealNames?r.name:'Zone '+(i+1),class:'region-zone'});destinationEvents(p,r.code);p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place(selected,r.code);}});map.append(p);const t=svg('text',{x:r.x,y:r.y,'text-anchor':'middle','pointer-events':'none'});t.textContent=String(i+1);map.append(t);});board.append(map);if(a.revealNames){const legend=element('div',undefined,'region-legend');regions.filter(r=>!r.overseas).forEach((r,i)=>legend.append(element('p',String(i+1)+' · '+r.name)));board.append(legend);}const overseas=element('div',undefined,'overseas');a.regions.filter(r=>r.code.length===3).forEach((r,i)=>{const b=element('button',a.revealNames?r.name:'Territoire '+(i+1),'destination');const geo=regions.find(x=>x.code===r.code);if(geo){const inset=svg('svg',{viewBox:'0 0 180 160',class:'overseas-map','aria-hidden':'true'});inset.append(svg('path',{d:geo.path,fill:'#badfd1',stroke:'#628aab','stroke-width':1}));b.prepend(inset);}b.prepend(element('span',['🌴 Antilles · archipel au nord de la Martinique','🌴 Antilles · île au sud de la Guadeloupe','🌳 Amérique du Sud','🌋 Océan Indien · à l’est de Madagascar','🏝️ Océan Indien · archipel des Comores'][i],'location-hint'));destinationEvents(b,r.code);overseas.append(b);});board.append(element('h3','Territoires ultramarins · encarts non à l’échelle'),overseas);root.append(board,element('p','Carte : contours France-GeoJSON (Etalab 2.0). Les encarts ultramarins indiquent les repères géographiques ; ils ne représentent pas les distances.','note'));}
function payment(a){root.append(element('p',a.explanation,'scenario'));const machine=element('div',undefined,'terminal'),display=element('output','40,00 €','terminal-display'),actions=element('div',undefined,'cards'),question=element('div',undefined,'quiz-options');machine.append(element('h3','Terminal d’entraînement'),display);root.append(machine,actions);const labels=['Carte Vitale · transmettre mes droits','Attestation de mutuelle · vérifier la part complémentaire','Carte bancaire · régler le reste'];labels.forEach((label,i)=>{const b=element('button',label,'card');b.onclick=()=>{if(stageReady||b.disabled)return;const ok=i===paymentStep;firstTry('pay'+paymentStep,ok);if(!ok){message('Dans cette simulation, vérifiez d’abord les prises en charge avant de régler le reste.');return;}paymentStep++;b.disabled=true;b.classList.add('done');const amounts=[16,4,0];display.textContent=amounts[i].toFixed(2).replace('.',',')+' €';message(['24 € sont versés directement par l’Assurance maladie dans cet exemple. La carte Vitale ne paie pas.','12 € sont versés directement par la complémentaire dans cet exemple. Il reste 4 € à régler.','Le paiement de 4 € solde la dépense fictive. Vérifiez maintenant votre compréhension.'][i],true);if(i===2){root.append(element('h3','Pourquoi le montant à avancer a-t-il diminué ?'),question);for(const choice of ['Parce que les organismes paient directement leurs parts dans cet exemple','Parce que la carte Vitale contient de l’argent']){const q=element('button',choice);q.onclick=()=>{if(stageReady)return;const ok=choice.startsWith('Parce que les organismes');firstTry('pay-understanding',ok);question.querySelectorAll('button').forEach(x=>x.disabled=true);message(ok?'Exact : il s’agit du tiers payant, selon la situation et les parts prises en charge.':'La carte Vitale ne contient pas d’argent. Les organismes paient directement leurs parts dans cet exemple.',ok);finish(statusBox.textContent);};question.append(q);}}};actions.append(b);});}
function correction(){if(!lesson||step>=2)return;const a=lesson.activities[step],host=document.querySelector('#correction');host.replaceChildren(element('h3','Correction expliquée'));if(!reviewed.includes(step))reviewed.push(step);store();if(a.type==='geo'){for(const [name,e]of [['Seine','Traverse Paris et rejoint la Manche.'],['Loire','Rejoint l’Atlantique près de Saint-Nazaire.'],['Garonne','Passe par Toulouse et Bordeaux.'],['Rhône','Passe par Lyon et rejoint la Méditerranée.'],['Rhin','Longe une partie de la frontière est.'],['Alpes','Au sud-est.'],['Pyrénées','Au sud-ouest, à la frontière espagnole.'],['Massif central','Au centre-sud.'],['Jura','À l’est, près de la Suisse.'],['Vosges','Au nord-est, à l’ouest du Rhin.']])host.append(element('p',name+' — '+e));}
 else if(a.type==='memory')a.pairs.forEach(p=>host.append(element('p',p.join(' — '))));else if(a.type==='payment')host.append(element('p',a.explanation),element('p','40 − 24 = 16 € ; 16 − 12 = 4 € ; 4 € sont réglés par carte bancaire.'));else a.items.forEach(x=>{const row=element('div',undefined,'correction-row');let target=x.answer||x.target;if(a.type==='map')target=a.regions.find(r=>r.code===x.target)?.name||target;if(['scheme','cycle','care'].includes(a.type))target='Étape '+target;row.append(element('strong',(x.label||x.prompt)+' → '+target),element('p',x.explanation));if(x.work)row.prepend(element('p',x.work));host.append(row);});host.hidden=!host.hidden;document.querySelector('#correction-button').textContent=host.hidden?'🔎 Accéder à la correction':'Masquer la correction';}
function render(){generation++;root.replaceChildren();next.hidden=true;document.querySelector('#correction').hidden=true;document.querySelector('#correction-button').hidden=step>=2;document.querySelector('#correction-button').textContent='🔎 Accéder à la correction';selected=null;placed=new Set();flipped=[];matched=new Set();locked=false;qi=0;answered=false;stageReady=false;counters={};paymentStep=0;update();if(step===2){document.querySelector('#activity-title').textContent='Vos deux activités sont terminées';document.querySelector('#instructions').textContent='Les questions de connaissances sont un exercice distinct, avec vos réponses écrites.';root.append(element('p','Vous pouvez maintenant écrire vos réponses dans le chatbot.','summary'));if(total)root.append(element('p','Premières réponses justes : '+score+'/'+total+'. Ce repère concerne les exercices comptabilisés ; le jeu de mémoire et les cartes géographiques ont leur propre progression.'));if(reviewed.length)root.append(element('p','Vous avez consulté le corrigé de '+reviewed.length+' activité(s). Recommencez plus tard sans le corrigé pour confirmer vos acquis.'));message('Choisissez une rubrique ci-dessous.',true);return;}
 const a=lesson.activities[step];document.querySelector('#activity-title').textContent=(step+1)+'. '+a.title;document.querySelector('#instructions').textContent=['cases','binary','phone','payment'].includes(a.type)?'Lisez la situation, faites votre choix et consultez l’explication.':a.type==='scratch'?'Grattez l’œuvre avec la souris ou le doigt, puis identifiez son auteur. Une alternative au clavier est disponible.':a.type==='connect'?'Cliquez sur une notion à gauche puis sur sa définition à droite.':a.type==='memory'?'Retournez deux cartes pour retrouver une paire.':['scheme','care','cycle'].includes(a.type)?'Choisissez les étapes dans l’ordre pour construire le schéma.':'Déplacez les étiquettes, ou cliquez sur une étiquette puis sur sa destination. Le clavier fonctionne avec Tab et Entrée.';
 if(a.type==='memory')memory(a);else if(['cases','binary','phone','scratch'].includes(a.type))cases(a);else if(['scheme','care','cycle'].includes(a.type))scheme(a);else if(a.type==='connect')connect(a);else if(a.type==='payment')payment(a);else if(a.type==='map')mapActivity(a);else if(a.type==='geo'){const f=element('iframe');f.src='../activites-geographie/?mode='+a.mode;f.title=a.title;root.append(f);}else placement(a);message('À vous de jouer. Le corrigé reste accessible à tout moment.');}
next.onclick=()=>{const a=lesson.activities[step];if(!a)return;if(['cases','binary','phone','scratch'].includes(a.type)&&answered){qi++;if(qi<a.items.length){next.hidden=true;cases(a);message('Situation suivante.');return;}stageReady=true;}if(!stageReady)return;step++;checkpointScore=score;checkpointTotal=total;if(step===2)complete();else store();render();};
document.querySelector('#correction-button').onclick=correction;
document.querySelector('#restart').onclick=()=>{step=0;score=0;total=0;checkpointScore=0;checkpointTotal=0;reviewed=[];try{localStorage.removeItem('nova-activity-'+chapter);}catch(e){}send({reset:true});store();render();};
document.querySelector('#notions').onclick=()=>navigation(chapter+'_GLO');document.querySelector('#questions').onclick=()=>{if(step===2)navigation(chapter+'_VERIF');};document.querySelector('#chapters').onclick=()=>navigation(chapter.replace(/_CH\d+$/,'_MENU'));document.querySelector('#main-menu').onclick=()=>navigation('MENU_PRINCIPAL');
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.source===parent&&e.data?.source==='nova-progress'&&e.data.chapter===chapter&&lesson){if(e.data.activityState){try{const s=JSON.parse(e.data.activityState);if(s.version===16&&Number.isInteger(s.step)&&s.step>=0&&s.step<=2){step=s.step;score=Number(s.score)||0;total=Number(s.total)||0;checkpointScore=score;checkpointTotal=total;reviewed=Array.isArray(s.reviewed)?s.reviewed:[];render();}}catch(err){}}else if(e.data.complete===true){step=2;render();}return;}const frame=root.querySelector('iframe');if(frame&&e.source===frame.contentWindow&&e.data?.source==='nova-activity'&&e.data.complete===true&&lesson?.activities[step]?.type==='geo'&&e.data.geoMode===lesson.activities[step].mode)finish();});
Promise.all([fetch('data.json?v=16').then(r=>{if(!r.ok)throw Error('Chapitre indisponible');return r.json();}),fetch('region-map.json?v=16').then(r=>{if(!r.ok)throw Error('Carte indisponible');return r.json();})]).then(([d,r])=>{lesson=d[chapter];regions=r;if(!lesson)throw Error('Chapitre indisponible');document.querySelector('#title').textContent=lesson.title;try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&s.version===16&&Number.isInteger(s.step)&&s.step>=0&&s.step<=2){step=s.step;score=Number(s.score)||0;total=Number(s.total)||0;checkpointScore=score;checkpointTotal=total;reviewed=Array.isArray(s.reviewed)?s.reviewed:[];}}catch(e){}render();if(step===2&&parent===window)complete();send({requestProgress:true});}).catch(e=>message('Les activités n’ont pas pu être chargées. '+e.message));

if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>send({resize:true,height:Math.max(400,Math.ceil(document.querySelector('main').getBoundingClientRect().height+24))})).observe(document.querySelector('main'));
