'use strict';
(function(root){
const doc=root.document,KEY='civicoach-accessibilite-v1',names=['contrast','markers','large','motion'];const profiles=['general','deuteranopia','protanopia','tritanopia','achromatopsia'];let state={colourProfile:'general',contrast:false,markers:false,large:false,motion:root.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false};
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)for(const key of names)if(typeof saved[key]==='boolean')state[key]=saved[key];if(profiles.includes(saved?.colourProfile))state.colourProfile=saved.colourProfile;}catch(e){}
function decorate(){for(const box of doc.querySelectorAll('.admonition.success,.admonition.danger,.admonition.error')){const title=box.querySelector('.admonitionTitle');if(!title||title.querySelector('.civi-outcome'))continue;const span=doc.createElement('span');span.className='civi-outcome';span.textContent=box.classList.contains('success')?'Réussite — ':'À revoir — ';title.prepend(span);}}
function apply(persist=false){doc.documentElement.dataset.civiColourProfile=state.markers?state.colourProfile:'off';const select=doc.getElementById('a11y-colour-profile');if(select)select.value=state.colourProfile;for(const key of names)doc.documentElement.classList.toggle('civi-a11y-'+key,state[key]);for(const key of names){const button=doc.getElementById('a11y-'+key);if(button){button.setAttribute('aria-checked',String(state[key]));button.querySelector('.switch-state').textContent=state[key]?'Activé':'Désactivé';}}if(state.motion&&doc.body.classList.contains('typewriter-active'))root.NovaTyping?.finish();if(persist)try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}for(const frame of doc.querySelectorAll('iframe'))try{const url=new URL(frame.src,location.href);if(url.origin===location.origin)frame.contentWindow.postMessage({source:'civicoach-accessibilite',settings:state},location.origin);}catch(e){}decorate();}
doc.addEventListener('click',event=>{if(!event.target.closest('.civi-skip'))return;event.preventDefault();event.stopImmediatePropagation();doc.getElementById('chat').focus();doc.getElementById('chat').scrollIntoView({block:'start',behavior:'instant'});},true);
root.NovaAccess={motion:()=>state.motion,settings:()=>({...state})};
for(const key of names){const button=doc.getElementById('a11y-'+key);if(button)button.onclick=()=>{state[key]=!state[key];apply(true);const status=doc.getElementById('a11y-status');if(status)status.textContent=button.querySelector('.switch-label').textContent+' : '+(state[key]?'activé':'désactivé')+'.';};}
const profile=doc.getElementById('a11y-colour-profile');if(profile)profile.addEventListener('change',()=>{if(!profiles.includes(profile.value))return;state.colourProfile=profile.value;state.markers=true;apply(true);const status=doc.getElementById('a11y-status');if(status)status.textContent='Mode Daltonisme activé : '+profile.selectedOptions[0].textContent+'.';});
const reset=doc.getElementById('a11y-reset');if(reset)reset.onclick=()=>{state={colourProfile:'general',contrast:false,markers:false,large:false,motion:root.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false};apply(true);};
root.addEventListener('storage',event=>{if(event.key!==KEY||!event.newValue)return;try{const incoming=JSON.parse(event.newValue);for(const key of names)if(typeof incoming[key]==='boolean')state[key]=incoming[key];if(profiles.includes(incoming.colourProfile))state.colourProfile=incoming.colourProfile;apply();}catch(e){}});
root.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==root.parent||event.data?.source!=='civicoach-accessibilite')return;for(const key of names)if(typeof event.data.settings?.[key]==='boolean')state[key]=event.data.settings[key];if(profiles.includes(event.data.settings.colourProfile))state.colourProfile=event.data.settings.colourProfile;apply();});
let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;decorate();});}).observe(doc.body,{childList:true,subtree:true});doc.addEventListener('load',event=>{if(event.target.tagName==='IFRAME')apply();},true);apply();
})(window);
