'use strict';
(function(root){
const doc=root.document,KEY='civicoach-accessibilite-v1',names=['contrast','markers','large','motion','audio','hover'];const profiles=['general','deuteranopia','protanopia','tritanopia','achromatopsia'];let state={colourProfile:'general',contrast:false,markers:false,large:false,audio:false,hover:false,motion:root.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false};
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)for(const key of names)if(typeof saved[key]==='boolean')state[key]=saved[key];if(profiles.includes(saved?.colourProfile))state.colourProfile=saved.colourProfile;}catch(e){}
// Un nouvel onglet peut disposer d’un stockage distinct de celui de l’iframe Moodle.
try{const transferred=root.NovaSave?.exportData?.().accessibility;if(transferred){for(const key of names)if(typeof transferred[key]==='boolean')state[key]=transferred[key];if(profiles.includes(transferred.colourProfile))state.colourProfile=transferred.colourProfile;}}catch(e){}
function decorate(){for(const box of doc.querySelectorAll('.admonition.success,.admonition.danger,.admonition.error')){const title=box.querySelector('.admonitionTitle');if(!title||title.querySelector('.civi-outcome'))continue;const span=doc.createElement('span');span.className='civi-outcome';span.textContent=box.classList.contains('success')?'Réussite — ':'À revoir — ';title.prepend(span);}}
function apply(persist=false){doc.documentElement.dataset.civiColourProfile=state.markers?state.colourProfile:'off';const select=doc.getElementById('a11y-colour-profile');if(select)select.value=state.colourProfile;for(const button of doc.querySelectorAll('[data-colour-profile]')){const on=state.markers&&state.colourProfile===button.dataset.colourProfile;button.setAttribute('aria-checked',String(on));button.querySelector('.switch-state').textContent=on?'Activé':'Désactivé';}for(const key of names)doc.documentElement.classList.toggle('civi-a11y-'+key,state[key]);for(const key of names){const button=doc.getElementById('a11y-'+key);if(button){button.setAttribute('aria-checked',String(state[key]));button.querySelector('.switch-state').textContent=state[key]?'Activé':'Désactivé';}}if(state.motion&&doc.body.classList.contains('typewriter-active'))root.NovaTyping?.finish();if(persist)try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}for(const frame of doc.querySelectorAll('iframe'))try{const url=new URL(frame.src,location.href);if(url.origin===location.origin)frame.contentWindow.postMessage({source:'civicoach-accessibilite',settings:state},location.origin);}catch(e){}decorate();icons(doc.getElementById('chat'));root.dispatchEvent(new CustomEvent('civicoach-accessibility-change',{detail:{...state}}));if(persist)root.NovaResume?.captureLive();}
doc.addEventListener('click',event=>{if(!event.target.closest('.civi-skip'))return;event.preventDefault();event.stopImmediatePropagation();doc.getElementById('chat').focus();doc.getElementById('chat').scrollIntoView({block:'start',behavior:'instant'});},true);
function icons(node){if(!node)return;const adapted=state.markers||state.contrast;for(const icon of node.querySelectorAll('.civi-emoji[data-civi-icon]')){const emoji=Object.keys(root.NovaIcons?.emojis||{}).find(e=>root.NovaIcons.emojis[e]===icon.dataset.civiIcon);if(!adapted&&emoji){icon.textContent=emoji;delete icon.dataset.civiIcon;icon.removeAttribute('aria-hidden');}}const walker=doc.createTreeWalker(node,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const text of nodes){if(text.parentElement.closest('script,style,code,pre')||text.parentElement.closest('.civi-emoji[data-civi-icon]'))continue;const regex=/(\p{Regional_Indicator}{2}|\p{Extended_Pictographic}(?:\uFE0F|\p{Emoji_Modifier}|\u200D\p{Extended_Pictographic})*)/gu;const chunks=[...text.textContent.matchAll(regex)];if(!chunks.length)continue;if(text.parentElement.classList.contains('civi-emoji')&&!adapted)continue;const frag=doc.createDocumentFragment();let i=0;for(const m of chunks){frag.append(doc.createTextNode(text.textContent.slice(i,m.index)));const span=doc.createElement('span');span.className='civi-emoji';const key=root.NovaIcons?.emojis[m[0]];if(key&&adapted){span.innerHTML=root.NovaIcons.svg[key];span.setAttribute('aria-hidden','true');span.dataset.civiIcon=key;}else span.textContent=m[0];frag.append(span);i=m.index+m[0].length;}frag.append(doc.createTextNode(text.textContent.slice(i)));text.replaceWith(frag);}}
root.NovaAccess={icons,importSettings:value=>{if(!value)return;for(const key of names)if(typeof value[key]==='boolean')state[key]=value[key];if(profiles.includes(value.colourProfile))state.colourProfile=value.colourProfile;apply();},motion:()=>state.motion,settings:()=>({...state})};
for(const key of names){const button=doc.getElementById('a11y-'+key);if(button)button.onclick=()=>{state[key]=!state[key];apply(true);const status=doc.getElementById('a11y-status');if(status)status.textContent=button.querySelector('.switch-label').textContent+' : '+(state[key]?'activé':'désactivé')+'.';};}
for(const button of doc.querySelectorAll('[data-colour-profile]'))button.addEventListener('click',()=>{const profile=button.dataset.colourProfile;if(!profiles.includes(profile))return;const was=state.markers&&state.colourProfile===profile;state.colourProfile=profile;state.markers=!was;apply(true);const status=doc.getElementById('a11y-status');if(status)status.textContent=button.getAttribute('aria-label')+' : '+(!was?'activé':'désactivé')+'.';});
const profile=doc.getElementById('a11y-colour-profile');if(profile)profile.addEventListener('change',()=>{if(!profiles.includes(profile.value))return;state.colourProfile=profile.value;state.markers=true;apply(true);const status=doc.getElementById('a11y-status');if(status)status.textContent='Mode Daltonisme activé : '+profile.selectedOptions[0].textContent+'.';});
const reset=doc.getElementById('a11y-reset');if(reset)reset.onclick=()=>{state={colourProfile:'general',contrast:false,markers:false,large:false,audio:false,hover:false,motion:root.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false};apply(true);};
root.addEventListener('storage',event=>{if(event.key!==KEY||!event.newValue)return;try{const incoming=JSON.parse(event.newValue);for(const key of names)if(typeof incoming[key]==='boolean')state[key]=incoming[key];if(profiles.includes(incoming.colourProfile))state.colourProfile=incoming.colourProfile;apply();}catch(e){}});
root.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==root.parent||event.data?.source!=='civicoach-accessibilite')return;for(const key of names)if(typeof event.data.settings?.[key]==='boolean')state[key]=event.data.settings[key];if(profiles.includes(event.data.settings.colourProfile))state.colourProfile=event.data.settings.colourProfile;apply();});
let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;decorate();if(!root.NovaBoot)icons(doc.body);});}).observe(doc.body,{childList:true,subtree:true});doc.addEventListener('load',event=>{if(event.target.tagName==='IFRAME')apply();},true);if(root.NovaBoot){const rendered=root.NovaBoot.rendered;root.NovaBoot.rendered=function(node){rendered?.call(this,node);icons(node);};}else icons(doc.body);apply();
})(window);
