'use strict';
(function(root){
const themes=['Principes et valeurs de la République','Institutions et système politique','Droits et devoirs','Histoire, géographie et culture','Vivre dans la société française'];
const methods=[
 ['Distinguez la liberté de chacun, les obligations de neutralité et les règles communes.','Décrivez une situation où ce principe protège une personne.'],
 ['Construisez un tableau « acteur / rôle / décision » : ne confondez pas celui qui propose, vote ou applique.','Expliquez qui intervient et à quel moment dans une décision publique.'],
 ['Classez les éléments en droits, obligations et interdictions, puis cherchez les conditions et les exceptions.','Expliquez quel droit est protégé et quelle obligation s’applique.'],
 ['Pour une date, utilisez une frise ; pour un lieu, une carte ; pour une œuvre, associez le titre, l’auteur et son contexte.','Replacez chaque repère dans une époque, un territoire ou un domaine culturel.'],
 ['Repérez la démarche, le bon interlocuteur et les documents ou conditions nécessaires.','Décrivez ce que vous feriez concrètement et à qui vous vous adresseriez.']];
const labels=['0–1/10 : identifier les premiers repères','2–3/10 : distinguer les notions proches','4–5/10 : expliquer ses choix','6–7/10 : renforcer le raisonnement','8–9/10 : lever les dernières hésitations','10/10 : transférer ses acquis'];
function missed(kind,t,v){const data=root.CiviFeedbackData||{questions:{},exam:{}},keys=[];
 if(kind==='examen'){for(let i=1;i<=40;i++)if(Number(v['lastErr'+i])===1){const key=data.exam['EXAM_'+v.lastExamCode+'_Q'+String(i).padStart(2,'0')];if(key)keys.push(key);}}
 else keys.push(...String(v[kind==='bilan'?'parcoursMistakes':'trainMistakes']||'').split('|').filter(Boolean));
 let choices={};try{choices=JSON.parse(v[kind==='bilan'?'parcoursFeedbackChoices':kind==='examen'?'lastFeedbackChoices':'trainFeedbackChoices']||'{}');}catch(e){}return [...new Set(keys)].map(k=>data.questions[k]?{...data.questions[k],key:k,chosen:choices[k]||null}:null).filter(q=>q&&q.theme===t);
}
function plan(kind,t,points,max,v={}){const pct=Math.max(0,Math.min(100,points/max*100)),band=Math.min(5,Math.floor(pct/20)),errors=points<max?missed(kind,t,v):[],notions=[...new Set(errors.map(q=>q.notion))];
 const focus=notions.length?'Relisez précisément : '+notions.slice(0,3).join(' ; ')+(notions.length>3?' ; puis les autres notions du corrigé.':'.'):points===max?'Aucune erreur dans cette thématique : travaillez un contexte différent.':'Relisez le corrigé de vos réponses manquées. Le détail des anciennes erreurs n’a pas été conservé pour cette tentative.';
 const method=methods[t-1]||methods[0],sample=errors[0]?'Reprenez la question : « '+errors[0].question+' » ':'';
 const actions=[
  [{title:'Identifier deux notions prioritaires',text:focus},{title:'Reformuler avec un exemple',text:sample+'Choisissez '+(errors.length===1?'cette erreur':'deux erreurs')+'. Expliquez la règle avec vos mots, puis donnez un exemple. '+method[0]},{title:'Réussir une courte vérification',text:'Refaites un entraînement de cette thématique après la révision. Premier objectif : quatre réponses justes sur dix, en expliquant les règles que vous venez de revoir.'},{title:'Retenir sans le cours',text:'Le lendemain, rappelez les deux règles sans regarder vos notes. Si une règle vous échappe, revoyez seulement cette notion.'}],
  [{title:'Séparer les notions confondues',text:focus},{title:'Comparer deux réponses proches',text:sample+'Notez ce qui distingue la bonne réponse de votre choix. '+method[0]},{title:'Vérifier une distinction',text:'Dans « M’entraîner », choisissez cette thématique. Votre score actuel est de '+points+'/'+max+' ('+Math.round(pct)+' %). Visez cinq bonnes réponses sur dix et expliquez au moins deux corrections.'},{title:'Faire une fiche utile',text:'Créez une fiche avec une règle, un exemple et une confusion à éviter. Relisez-la après deux jours avant de vous retester.'}],
  [{title:'Cibler les erreurs répétées',text:focus},{title:'Justifier avant de valider',text:sample+method[1]+' Pour chaque question, justifiez votre choix avant de lire la correction.'},{title:'Améliorer la prochaine série',text:'Visez sept bonnes réponses sur une nouvelle série de dix questions. Prenez le temps d’expliquer deux propositions incorrectes.'},{title:'Réutiliser les connaissances',text:'Inventez une situation où la règle s’applique. Vérifiez votre raisonnement dans le cours plutôt que de retenir une lettre de réponse.'}],
  [{title:'Travailler les points hésitants',text:focus},{title:'Comparer deux contextes',text:sample+method[0]+' Cherchez ce qui change lorsque le contexte de la question change.'},{title:'Stabiliser le raisonnement',text:'Sur une nouvelle série, cherchez au moins 80 % de bonnes réponses et justifiez les réponses sur vos notions fragiles.'},{title:'Vérifier à distance',text:'Après 48 heures, expliquez trois règles sans vos notes. Passez ensuite un examen blanc pour observer leur application dans une série complète.'}],
  [{title:'Résoudre les dernières erreurs',text:focus},{title:'Expliquer la limite ou l’exception',text:sample+'Repérez le mot ou la condition qui change la réponse. '+method[1]},{title:'Valider une maîtrise ciblée',text:'Répondez à trois nouvelles questions sur vos derniers points faibles, sans consulter le cours. Cherchez trois réponses correctes et justifiées.'},{title:'Confirmer en conditions réelles',text:'Passez un examen blanc chronométré. L’objectif est d’atteindre au moins 32/40 tout en évitant les confusions identifiées ici.'}],
  [{title:'Conserver vos repères',text:focus},{title:'Transférer la règle',text:method[1]+' Imaginez un exemple différent de celui rencontré dans la série.'},{title:'Choisir un défi nouveau',text:'Réalisez trois mises en situation ou des questions difficiles. Expliquez la règle et éliminez les propositions qui ne la respectent pas.'},{title:'Entretenir dans le temps',text:'Une semaine plus tard, vérifiez ces notions dans une nouvelle série mélangée. L’objectif est de conserver votre raisonnement, même avec un ordre de réponses différent.'}]
 ][band];
 const specific=methodFor(errors,t);if(errors.length){actions[1].text=specific;actions[0].title='Identifier vos erreurs prioritaires';}
 if(band<5){actions.push({title:band<2?'Revenir sur vos nouvelles erreurs':band<4?'Vérifier ce qui progresse':'Entretenir les acquis',text:band<2?'Après le nouvel entraînement, comparez vos erreurs avec celles-ci. Notez une règle et un exemple pour chaque confusion persistante ; puis cherchez huit réponses justes sur dix dans une série différente.':band<4?'Comparez la nouvelle correction à celle de cette tentative. Si la même notion reste fragile, revoyez son chapitre ; sinon, passez aux autres notions sans refaire toute la thématique.':'Deux jours plus tard, expliquez les règles associées à vos erreurs sans vos notes. Travaillez une nouvelle situation si vous hésitez encore.'});}
 return {band,label:labels[band],steps:actions,errors,notions};}
function methodFor(errors,t){const q=errors.map(e=>e.notion+' '+e.question).join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const guides=[[/laic|neutralite|religion|conscience/,'Pour chaque situation de laïcité, distinguez la personne, son rôle et le lieu : agent public, usager ou élève. Notez ce qui relève de la neutralité de l’État et ce qui relève de la liberté de conscience.'],[/gouvernement|parlement|president|premier ministre/,'Reprenez le chapitre sur les institutions. Faites trois colonnes : qui propose, qui vote, qui applique. Replacez la décision de votre question dans ce schéma, puis expliquez pourquoi votre autre choix ne convient pas.'],[/vote|election|electeur/,'Repérez dans votre question le type d’élection et la personne concernée. Faites une fiche « qui peut voter / à quelle élection / sous quelles conditions », puis confrontez-la au corrigé.'],[/drapeau|marianne|devise|symbole|hymne|14 juillet/,'Revenez aux symboles de la République. Associez chaque symbole à sa fonction ou à sa signification. Vérifiez surtout la distinction entre un symbole républicain et un élément culturel français.'],[/camus|yourcenar|hugo|auteur|ecrivain|peint|oeuvre|tableau/,'Dans le chapitre Patrimoine et culture, associez chaque œuvre à son auteur et à un repère de contexte. Cachez les noms pour refaire l’activité, puis expliquez ce qui vous permet de reconnaître cette œuvre.'],[/date|revolution|guerre|siecle|napoleon|histoire/,'Replacez l’événement manqué sur une frise. Ajoutez un événement qui le précède et un qui le suit, puis racontez ce qui change à cette période.'],[/fleuve|region|territoire|geograph|departement|capitale/,'Sur la carte du cours, retrouvez le lieu ou le trajet concerné. Décrivez sa position par rapport à deux repères connus, puis recherchez-le à nouveau sans regarder la correction.'],[/travail|salaire|emploi|employeur|contrat/,'Dans le chapitre Emploi, reprenez la règle liée à votre erreur. Distinguez les obligations, les droits et les conditions d’application ; pour une fiche de paie, vérifiez le libellé de chaque montant avant le calcul.'],[/sante|soin|assurance maladie|vitale/,'Dans le chapitre Santé, identifiez la démarche et la prise en charge concernées. Reformulez ce que la personne doit faire, puis distinguez le coût, le remboursement et le montant restant à payer.'],[/parent|enfant|ecole|scolar|education/,'Reprenez le chapitre correspondant à la famille ou à la scolarité. Identifiez qui est responsable, ce qui est obligatoire et ce qui dépend de la situation de l’enfant.'],[/droit|devoir|interdit|autorise|obligat|discrimination/,'Relisez la correction en repérant le droit protégé et ses conditions. Soulignez les mots « interdit », « autorisé » ou « obligatoire » : une proposition partiellement vraie peut être incorrecte dans ce contexte.']];
 return (guides.find(([test])=>test.test(q))?.[1]||(methods[t-1]||methods[0])[0])+' Comparez votre choix à la réponse correcte avant de vous retester.';
}

function render(node){if(!root.NovaSave||!node)return;const v=root.NovaSave.exportData().variables;
 for(const host of node.querySelectorAll('.civi-feedback')){if(host.dataset.ready)continue;host.dataset.ready='true';const kind=host.dataset.kind,ts=host.dataset.theme==='all'?[1,2,3,4,5]:[Number(host.dataset.theme)];
 const rows=ts.map(t=>{const prefix=kind==='bilan'?'parcours':kind==='examen'?'last':'train',raw=v[prefix+'T'+t],total=kind==='bilan'?5:v[(kind==='examen'?'lastTotal':'trainTotal')+t];return {t,points:Number(raw),max:Number(total),valid:raw!=null&&total!=null};}).filter(x=>x.valid&&Number.isFinite(x.points)&&x.max>0).sort((a,b)=>a.points/a.max-b.points/b.max||a.t-b.t);
 for(const row of rows){const p=plan(kind,row.t,row.points,row.max,v),box=document.createElement('section');box.className='civi-feedback-card';const title=document.createElement('h4');title.textContent='🎯 '+themes[row.t-1]+' · '+row.points+'/'+row.max;box.append(title);const band=document.createElement('p');band.textContent='🧭 Votre prochaine étape : '+p.label;box.append(band);if(p.errors.length){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='🔎 '+p.errors.length+' erreur(s) à comprendre';details.append(summary);for(const error of p.errors){const item=document.createElement('p');item.textContent='Question : '+error.question+(error.chosen?' — Votre choix : '+error.chosen:'')+(error.correct?' — Réponse correcte : '+error.correct:'');details.append(item);}box.append(details);}const list=document.createElement('ol');for(const step of p.steps){const item=document.createElement('li'),strong=document.createElement('strong'),text=document.createElement('p');strong.textContent=['🔎 ','📖 ','🎯 ','⏱️ ','✍️ '][p.steps.indexOf(step)]+step.title;text.textContent=step.text;item.append(strong,text);list.append(item);}box.append(list);
 const links=[...new Map(p.errors.map(q=>[q.course,q])).values()].slice(0,3);for(const q of links){const a=document.createElement('a');a.href='#'+root.btoa(q.course);a.textContent='📖 Revoir : '+q.notion;a.addEventListener('click',event=>{if(!root.NovaRuntime?.navigate)return;event.preventDefault();event.stopImmediatePropagation();root.NovaRuntime.navigate(q.course);});box.append(a);}host.append(box);}
 }}
root.NovaFeedback={plan,missed,render,methodFor};
function init(){if(!root.NovaBoot)return;document.addEventListener('click',event=>{const link=event.target.closest?.('#chat a');if(!link)return;const marker=link.closest('.bot-message')?.querySelector('[data-civi-question]');if(!marker)return;let target;try{target=root.atob(link.hash.slice(1));}catch(e){return;}if(target!==marker.dataset.screen+'_FAUX')return;root.NovaSave?.recordMistake(marker.dataset.kind,marker.dataset.civiQuestion,link.textContent.replace(/^[A-D]\s*/,''));},true);const old=root.NovaBoot.rendered;root.NovaBoot.rendered=function(node){old?.call(this,node);render(node);root.NovaAccess?.icons(node);};}
if(root.document){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();}
})(window);
