'use strict';
(function(root){
const doc=root.document,synth=root.speechSynthesis;let queue=[],active=null,token=0,hoverTimer=0,activityTimer=0,lastActivity='',lastSpoken='',wasAudio=false;
const settings=()=>root.NovaAccess?.settings?.()||{};
function report(text){const box=doc.getElementById('a11y-status');if(box)box.textContent=text;}
function content(node){if(!node)return '';const copy=node.cloneNode(true);for(const el of copy.querySelectorAll('script,style,[hidden],[aria-hidden="true"],canvas,.civi-message-mascot,.civi-audio-controls'))el.remove();for(const img of copy.querySelectorAll('img'))img.replaceWith(doc.createTextNode(img.alt||''));for(const frame of copy.querySelectorAll('iframe'))frame.replaceWith(doc.createTextNode(' Activité interactive. Entrez dans l’activité pour entendre sa description. '));for(const el of copy.querySelectorAll('p,li,h1,h2,h3,h4,button,td,th,section'))el.append(doc.createTextNode('. '));return copy.textContent.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'').replace(/\s+/g,' ').trim();}
function stop(){token++;queue=[];active=null;if(synth)synth.cancel();doc.querySelectorAll('.civi-reading').forEach(el=>el.classList.remove('civi-reading'));}
function speak(value,node){if(!synth||!root.SpeechSynthesisUtterance){report('Lecture audio indisponible dans ce navigateur. Utilisez votre lecteur d’écran.');return false;}const text=String(value||'').trim();if(!text)return false;stop();const run=token;lastSpoken=text;queue=text.match(/.{1,210}(?:\s|$)|.{1,210}/g)||[text];if(node){node.classList.add('civi-reading');active=node;}function next(){if(run!==token)return;if(!queue.length){active?.classList.remove('civi-reading');active=null;return;}const utterance=new root.SpeechSynthesisUtterance(queue.shift());utterance.lang='fr-FR';utterance.rate=1;const voice=synth.getVoices().find(v=>/^fr[-_]/i.test(v.lang));if(voice)utterance.voice=voice;utterance.onend=next;utterance.onerror=e=>{if(run!==token||e.error==='canceled'||e.error==='interrupted')return;stop();report('La lecture n’a pas démarré. Cliquez sur « Lire la réponse » ou utilisez votre lecteur d’écran.');};synth.speak(utterance);}next();return true;}
function current(){return [...doc.querySelectorAll('#chat .bot-message')].at(-1)||doc.querySelector('main')||doc.body;}
function readCurrent(){root.NovaTyping?.finish();const node=current();speak(content(node),node);}
function annotate(){if(!settings().hover)return;for(const el of doc.querySelectorAll('#chat .bot-message p,#chat .bot-message h3,.panel p,.panel h2,.panel h3,[data-audio-description]'))if(!el.hasAttribute('tabindex')){el.tabIndex=0;el.dataset.civiAudioFocus='true';}}
function changed(){const s=settings();if(s.audio&&!wasAudio)readCurrent();wasAudio=s.audio;if(!s.audio&&!s.hover)stop();if(!s.hover){clearTimeout(hoverTimer);for(const el of doc.querySelectorAll('[data-civi-audio-focus]')){el.removeAttribute('tabindex');delete el.dataset.civiAudioFocus;}}annotate();}
function target(event){const el=event.target?.closest?.('[data-audio-description],button,a,p,li,h1,h2,h3,h4,td,th,[role="button"]');return el&&!el.closest('.civi-audio-controls,#controls,#civicoach-loading')?el:null;}
function hover(event){if(!settings().hover)return;const el=target(event);if(!el||el.contains(event.relatedTarget))return;clearTimeout(hoverTimer);hoverTimer=root.setTimeout(()=>{if(!el.isConnected)return;const value=el.dataset.audioDescription||content(el);if(value&&value!==lastSpoken)speak(value,el);},450);}
doc.addEventListener('pointerover',hover);doc.addEventListener('focusin',hover);doc.addEventListener('pointerout',event=>{if(!event.target.contains(event.relatedTarget))clearTimeout(hoverTimer);});doc.addEventListener('focusout',()=>clearTimeout(hoverTimer));doc.addEventListener('keydown',event=>{if(event.key==='Escape')stop();});
root.addEventListener('civicoach-accessibility-change',changed);root.addEventListener('pagehide',stop);
root.NovaAudio={speak,stop,readCurrent,content,visualMode:()=>!!(settings().audio||settings().hover)};
for(const [id,fn] of [['audio-read',readCurrent],['audio-stop',stop],['audio-pause',()=>{if(!synth)return;if(synth.paused)synth.resume();else if(synth.speaking)synth.pause();}]]){const button=doc.getElementById(id);if(button)button.onclick=fn;}
function init(){if(root.NovaBoot){const old=root.NovaBoot.rendered;root.NovaBoot.rendered=function(node){old?.call(this,node);annotate();if(settings().audio&&node?.classList.contains('bot-message')&&!node.querySelector('.civicoach-route'))speak(content(node),node);};}else{const watch=new MutationObserver(()=>{clearTimeout(activityTimer);activityTimer=root.setTimeout(()=>{annotate();const node=doc.querySelector('.panel')||doc.querySelector('main');const value=content(node);if(settings().audio&&value&&value!==lastActivity){lastActivity=value;speak(value,node);}},650);});watch.observe(doc.querySelector('main')||doc.body,{subtree:true,childList:true,characterData:true});if(settings().audio)readCurrent();}changed();}
if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
