'use strict';
(function(root){
const doc=root.document,synth=root.speechSynthesis;let queue=[],active=null,token=0,hoverTimer=0,activityTimer=0,lastActivity='',lastSpoken='',wasAudio=false;
const settings=()=>root.NovaAccess?.settings?.()||{};
const controls=doc.querySelector('.civi-audio-controls');
if(controls){controls.id='civi-audio-dock';controls.setAttribute('role','toolbar');controls.setAttribute('aria-label','Commandes de lecture audio');doc.body.append(controls);
 for(const [id,icon,label] of [['audio-read','🔊','Lire la réponse'],['audio-pause','⏸','Pause / reprendre'],['audio-stop','⏹','Arrêter']]){const button=doc.getElementById(id);button.setAttribute('aria-label',label);button.title=label;button.replaceChildren();const symbol=doc.createElement('span');symbol.setAttribute('aria-hidden','true');symbol.textContent=icon;const text=doc.createElement('span');text.className='civi-audio-label';text.textContent=label;button.append(symbol,text);}
 function placeDock(){const input=doc.getElementById('controls');if(innerWidth<1100&&input){const bottom=Math.max(16,innerHeight-input.getBoundingClientRect().top+12);controls.style.bottom=Math.ceil(bottom)+'px';controls.style.top='auto';}else{controls.style.bottom='auto';controls.style.top='40%';}}
 root.addEventListener('resize',placeDock);root.visualViewport?.addEventListener('resize',placeDock);if(root.ResizeObserver&&doc.getElementById('controls'))new root.ResizeObserver(placeDock).observe(doc.getElementById('controls'));placeDock();}

function report(text){const box=doc.getElementById('a11y-status');if(box)box.textContent=text;}
function content(node){if(!node)return '';const copy=node.cloneNode(true);for(const el of copy.querySelectorAll('script,style,[hidden],[aria-hidden="true"],canvas,.civi-message-mascot,.civi-audio-controls'))el.remove();for(const img of copy.querySelectorAll('img'))img.replaceWith(doc.createTextNode(img.alt||''));for(const frame of copy.querySelectorAll('iframe'))frame.replaceWith(doc.createTextNode(' Activité interactive. Entrez dans l’activité pour entendre sa description. '));for(const el of copy.querySelectorAll('p,li,h1,h2,h3,h4,button,td,th,section'))el.append(doc.createTextNode('. '));return copy.textContent.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,'').replace(/\s+/g,' ').trim();}
function stop(){token++;queue=[];active=null;if(synth)synth.cancel();doc.querySelectorAll('.civi-reading').forEach(el=>el.classList.remove('civi-reading'));}
function speak(value,node){if(!synth||!root.SpeechSynthesisUtterance){report('Lecture audio indisponible dans ce navigateur. Utilisez votre lecteur d’écran.');return false;}const text=String(value||'').trim();if(!text)return false;stop();const run=token;lastSpoken=text;queue=text.match(/.{1,210}(?:\s|$)|.{1,210}/g)||[text];if(node){node.classList.add('civi-reading');active=node;}function next(){if(run!==token)return;if(!queue.length){active?.classList.remove('civi-reading');active=null;return;}const utterance=new root.SpeechSynthesisUtterance(queue.shift());utterance.lang='fr-FR';utterance.rate=1;const voice=synth.getVoices().find(v=>/^fr[-_]/i.test(v.lang));if(voice)utterance.voice=voice;utterance.onend=next;utterance.onerror=e=>{if(run!==token||e.error==='canceled'||e.error==='interrupted')return;stop();report('La lecture n’a pas démarré. Cliquez sur « Lire la réponse » ou utilisez votre lecteur d’écran.');};synth.speak(utterance);}next();return true;}
function current(){return [...doc.querySelectorAll('#chat .bot-message')].at(-1)||doc.querySelector('main')||doc.body;}
function readCurrent(){root.NovaTyping?.finish();const node=current();speak(content(node),node);}
function annotate(){if(!settings().hover)return;for(const el of doc.querySelectorAll('#chat .bot-message p,#chat .bot-message h3,.panel p,.panel h2,.panel h3,[data-audio-description]'))if(!el.hasAttribute('tabindex')){el.tabIndex=0;el.dataset.civiAudioFocus='true';}}
function changed(){const s=settings();if(s.audio&&!wasAudio)readCurrent();wasAudio=s.audio;if(!s.audio&&!s.hover)stop();if(!s.hover){clearTimeout(hoverTimer);for(const el of doc.querySelectorAll('[data-civi-audio-focus]')){el.removeAttribute('tabindex');delete el.dataset.civiAudioFocus;}}annotate();}
function target(event){const el=event.target?.closest?.('[data-audio-description],button,a,p,li,h1,h2,h3,h4,td,th,[role="button"]');return el&&!el.closest('.civi-audio-controls,#controls,#civicoach-loading')?el:null;}
function hover(event){if(!settings().hover)return;const el=target(event);if(!el||el.contains(event.relatedTarget))return;clearTimeout(hoverTimer);hoverTimer=root.setTimeout(()=>{if(!el.isConnected)return;const value=el.dataset.audioDescription||content(el);if(value&&value!==lastSpoken)speak(value,el);},450);}
doc.addEventListener('pointerover',hover);doc.addEventListener('focusin',hover);doc.addEventListener('pointerout',event=>{if(!event.target.contains(event.relatedTarget))clearTimeout(hoverTimer);});doc.addEventListener('focusout',()=>clearTimeout(hoverTimer));doc.addEventListener('keydown',event=>{if(event.key==='Escape')stop();});
root.addEventListener('civicoach-accessibility-change',changed);root.addEventListener('pagehide',stop);
root.NovaAudio={speak,stop,readCurrent,content,visualMode:()=>!!(settings().audio||settings().hover)};
for(const [id,fn] of [['audio-read',readCurrent],['audio-stop',stop],['audio-pause',()=>{if(!synth)return;if(synth.paused)synth.resume();else if(synth.speaking)synth.pause();}]]){const button=doc.getElementById(id);if(button)button.onclick=fn;}
function init(){if(root.NovaBoot){const old=root.NovaBoot.rendered;root.NovaBoot.rendered=function(node){old?.call(this,node);annotate();if(settings().audio&&node?.classList.contains('bot-message')&&!node.querySelector('.civicoach-route'))speak(content(node),node);};}else{const watch=new MutationObserver(()=>{clearTimeout(activityTimer);activityTimer=root.setTimeout(()=>{annotate();const node=doc.querySelector('.panel')||doc.querySelector('main');const value=content(node);if(settings().audio&&value&&value!==lastActivity){lastActivity=value;speak(value,node);}},650);});watch.observe(doc.querySelector('main')||doc.body,{subtree:true,childList:true,characterData:true});if(settings().audio)readCurrent();}changed();}
if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);

// Les réglages restent les mêmes : le panneau est déplacé, jamais dupliqué.
(function(root){
const doc=root.document,panel=doc.getElementById('a11y-panel'),dock=doc.getElementById('civi-audio-dock');if(!panel||!dock)return;
const home=panel.parentElement,placeholder=doc.createElement('span');placeholder.hidden=true;panel.before(placeholder);
const dialog=doc.createElement('dialog');dialog.id='civi-settings-dialog';dialog.setAttribute('aria-labelledby','civi-settings-title');dialog.innerHTML='<div class="civi-settings-heading"><h2 id="civi-settings-title">⚙️ Réglages d’accessibilité</h2><button type="button" aria-label="Fermer les réglages" id="civi-settings-close">✕</button></div>';doc.body.append(dialog);
const gear=doc.createElement('button');gear.id='civi-settings-open';gear.type='button';gear.title='Paramètres d’accessibilité';gear.setAttribute('aria-label','Ouvrir les paramètres d’accessibilité');gear.setAttribute('aria-haspopup','dialog');gear.setAttribute('aria-controls',dialog.id);gear.setAttribute('aria-expanded','false');gear.innerHTML='<span aria-hidden="true">⚙️</span><span class="civi-audio-label">Paramètres</span>';dock.append(gear);let returnFocus=gear;
function afterClose(){placeholder.before(panel);gear.setAttribute('aria-expanded','false');returnFocus?.focus({preventScroll:true});}
function close(){if(dialog.open&&dialog.close)dialog.close();else{dialog.removeAttribute('open');afterClose();}}
gear.onclick=()=>{returnFocus=doc.activeElement;root.NovaAudio?.stop();dialog.append(panel);if(home.tagName==='DETAILS')home.open=false;gear.setAttribute('aria-expanded','true');if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');doc.getElementById('civi-settings-close').focus();};
doc.getElementById('civi-settings-close').onclick=close;dialog.addEventListener('close',afterClose);dialog.addEventListener('cancel',()=>root.NovaAudio?.stop());dialog.addEventListener('keydown',event=>{if(event.key==='Escape'&&!dialog.showModal){event.preventDefault();close();}if(event.key==='Tab'){const buttons=[...dialog.querySelectorAll('button,[href],input,select,[tabindex="0"]')].filter(b=>!b.disabled&&!b.hidden);const first=buttons[0],last=buttons.at(-1);if(event.shiftKey&&doc.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&doc.activeElement===last){event.preventDefault();first?.focus();}}});
})(window);

(function(root){function init(){const dock=root.document.getElementById('civi-audio-dock');if(!dock||root.document.getElementById('civi-open-full'))return;const button=root.document.createElement('button');button.id='civi-open-full';button.type='button';button.textContent='⤢';button.title='Ouvrir CiviCoach en grand dans un nouvel onglet';button.setAttribute('aria-label',button.title);button.hidden=root.parent===root;button.onclick=()=>{root.NovaAudio?.stop();root.NovaSave?.openFull();};dock.append(button);dock.setAttribute('aria-label','Lecture, accessibilité et affichage de CiviCoach');}if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',init,{once:true});else init();})(window);
