'use strict';
(function(root){
const tabId=root.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);let revision=1,sequence=0,owner=tabId,seen=1;
const doc=root.document,results=new URLSearchParams(location.search).get('vue')==='resultats';
function mascot(node){if(!node?.classList.contains('bot-message')||node.querySelector('.civi-message-mascot'))return;const heading=node.querySelector('h1,h2,h3,h4,p');if(!heading)return;const image=doc.createElement('img');image.className='civi-message-mascot';image.src=new URL('../Mascotteredim.png',location.href).href;image.alt='';image.width=40;image.height=48;image.setAttribute('aria-hidden','true');heading.prepend(image);}
function tables(){for(const table of doc.querySelectorAll('#chat table')){if(table.parentElement.classList.contains('civi-table-scroll'))continue;const box=doc.createElement('div');box.className='civi-table-scroll';box.tabIndex=0;box.setAttribute('role','region');box.setAttribute('aria-label','Tableau : faites défiler horizontalement pour lire toutes les colonnes');table.before(box);box.append(table);}}
let queued=false;new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;tables();});}}).observe(doc.getElementById('chat'),{childList:true,subtree:true});
function capture(){if(owner!==tabId)return;const chat=doc.getElementById('chat');if(!chat.children.length)return;let nodes=[...chat.children],html=nodes.map(n=>n.outerHTML).join('');while(html.length>600000&&nodes.length>2){nodes.shift();html=nodes.map(n=>n.outerHTML).join('');}root.NovaSave.setResume({actor:owner,revision,sequence:++sequence,html,variables:root.NovaSave.exportData().variables,scroll:root.scrollY,chatScroll:chat.scrollTop,controlsHidden:doc.body.classList.contains('hideControls'),examTimerEnd:Number(localStorage.getItem('chatmd_examen_fin'))||null,runtime:root.NovaRuntime?.exportSession(),help:root.NovaHelp?.exportSession(),updated:Date.now()});}
function safeHTML(value){const parsed=new DOMParser().parseFromString(value,'text/html');for(const el of parsed.body.querySelectorAll('*')){if(['SCRIPT','STYLE','OBJECT','EMBED','BASE','META','LINK','FORM'].includes(el.tagName)){el.remove();continue;}for(const a of [...el.attributes]){if(/^on/i.test(a.name)||['srcdoc','autofocus'].includes(a.name))el.removeAttribute(a.name);if(['href','src','action'].includes(a.name)){try{const u=new URL(a.value,location.href);if(!['https:','http:'].includes(u.protocol)||(el.tagName==='IFRAME'&&u.origin!==location.origin))el.removeAttribute(a.name);}catch(e){el.removeAttribute(a.name);}}}}for(const frame of parsed.body.querySelectorAll('iframe'))try{const url=new URL(frame.src,location.href);if(url.pathname.includes('/minuteur-examen/')){url.searchParams.delete('start');frame.src=url.href;}}catch(e){}return parsed.body.innerHTML;}
let resumed=false;const shouldResume=new URLSearchParams(location.search).get('reprendre')==='1';
const old=root.NovaBoot.rendered;
root.NovaBoot.rendered=function(node){old(node);mascot(node);if(!shouldResume||resumed||!node?.classList.contains('bot-message'))return;const state=root.NovaSave.exportData(),saved=state.resume;if(!saved||typeof saved.html!=='string'||saved.html.length>600000)return;resumed=true;setTimeout(()=>{const current=root.NovaSave.exportData();root.NovaSave.importData({...current,variables:saved.variables||state.variables},true);doc.getElementById('chat').innerHTML=safeHTML(saved.html);for(const message of doc.querySelectorAll('#chat .bot-message'))mascot(message);doc.body.classList.toggle('hideControls',!!saved.controlsHidden);tables();root.NovaRuntime?.importSession(saved.runtime);root.NovaHelp?.importSession(saved.help);doc.getElementById('civicoach-loading').hidden=true;setTimeout(()=>root.scrollTo(0,Number(saved.scroll)||0),100);},30);};
function returnFull(){if(root.opener&&!root.opener.closed){try{if(root.opener.location.origin===location.origin&&root.opener.parent===root.opener&&!new URLSearchParams(root.opener.location.search).has('vue')){root.opener.focus();root.close();return;}}catch(e){}}root.NovaLink.go('./?reprendre=1');}
let applying=false,latest=0,waiting=root.opener?root.NovaSave.exportData().resume:null;
function isNewer(saved){if(!saved)return false;if(saved.revision!=null){const r=Number(saved.revision)||0;seen=Math.max(seen,r);return r>revision||(r===revision&&(saved.actor===owner?Number(saved.sequence)>sequence:String(saved.actor)>owner));}return Number(saved.updated)>latest;}
function markLocal(){revision=Math.max(revision,seen)+1;seen=revision;sequence=0;owner=tabId;}
function applyLive(saved,force=false){if(results||!saved||typeof saved.html!=='string'||saved.html.length>600000||(!force&&!isNewer(saved)))return;if(!root.NovaRuntime||root.NovaBoot.isStarting()){waiting=saved;return;}applying=true;owner=saved.actor||'legacy';revision=Number(saved.revision)||0;seen=Math.max(seen,revision);sequence=Number(saved.sequence)||0;latest=Number(saved.updated);if(Number(saved.examTimerEnd)>0)try{localStorage.setItem('chatmd_examen_fin',String(saved.examTimerEnd));}catch(e){}root.NovaAudio?.stop();root.NovaTyping?.cancel?.();doc.getElementById('chat').innerHTML=safeHTML(saved.html);root.NovaRuntime.importSession(saved.runtime);doc.body.classList.toggle('hideControls',!!saved.controlsHidden);for(const message of doc.querySelectorAll('#chat .bot-message'))mascot(message);tables();root.NovaAccess?.icons(doc.getElementById('chat'));root.NovaHelp?.importSession(saved.help);doc.getElementById('civicoach-loading').hidden=true;doc.getElementById('chat').scrollTop=Number(saved.chatScroll)||0;if(doc.visibilityState==='visible')root.scrollTo(0,Number(saved.scroll)||0);applying=false;}
function captureLive(){if(applying||results||owner!==tabId||!root.NovaRuntime)return;capture();latest=Number(root.NovaSave.exportData().resume?.updated)||Date.now();root.NovaLink?.changed();}
const previous=root.NovaBoot.rendered;root.NovaBoot.rendered=function(node){previous.call(this,node);if(waiting){const saved=waiting;waiting=null;applyLive(saved,true);return;}if(node?.classList.contains('bot-message')&&!node.querySelector('.civicoach-route'))root.setTimeout(captureLive,60);};
root.NovaResume={capture,returnFull,applyLive,captureLive,isNewer,markLocal};
doc.addEventListener('click',event=>{if(event.target.closest?.('#send-button,#civi-help-anywhere,#civi-help-panel button,#a11y-panel button,#chat a'))markLocal();},true);doc.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target===doc.getElementById('user-input'))markLocal();},true);
root.addEventListener('civicoach-runtime-ready',()=>{if(waiting&&!root.NovaBoot.isStarting()){const saved=waiting;waiting=null;applyLive(saved,true);}});

const link=doc.createElement('link');link.rel='stylesheet';link.href='presentation.css?v=29';doc.head.append(link);
const show=doc.getElementById("civi-show-now");function placeShow(){if(!show)return;const controls=doc.getElementById('controls');let bottom=Math.max(16,innerHeight-controls.getBoundingClientRect().top+12);const waiting=doc.getElementById('question-loading');if(waiting&&!waiting.hidden)bottom=Math.max(bottom,innerHeight-waiting.getBoundingClientRect().top+12);show.style.bottom=Math.ceil(bottom)+'px';}if(root.ResizeObserver)new ResizeObserver(placeShow).observe(doc.getElementById('controls'));root.addEventListener('resize',placeShow);root.visualViewport?.addEventListener('resize',placeShow);placeShow();new MutationObserver(placeShow).observe(doc.getElementById('question-loading'),{attributes:true,attributeFilter:['hidden']});
if(show)show.onclick=()=>{root.NovaTyping?.finish();};
if(!results)root.addEventListener('pagehide',capture);
})(window);
