'use strict';
(function(root){
const doc=root.document;let open=false,replyToken=0,lastQuestion='';const bank=new Map((root.CiviQuestionsBank||[]).map(row=>[row.id,row]));
const trigger=doc.createElement('button');trigger.id='civi-help-anywhere';trigger.type='button';trigger.textContent='❓ Une question ?';trigger.setAttribute('aria-expanded','false');trigger.setAttribute('aria-controls','civi-help-panel');
const panel=doc.createElement('section');panel.id='civi-help-panel';panel.hidden=true;panel.setAttribute('role','region');panel.setAttribute('aria-label','Demander à CiviCoach sans quitter l’activité');panel.innerHTML='<div class="civi-help-heading"><h2>❓ Demander à CiviCoach</h2><button type="button" id="civi-help-close" aria-label="Fermer l’aide et continuer">✕</button></div><p>Votre activité reste ouverte. Posez votre question puis poursuivez là où vous en étiez.</p><div id="civi-help-answer" aria-live="polite"></div><form id="civi-help-form"><label for="civi-help-input">Votre question</label><div><input type="text" id="civi-help-input" maxlength="2500" autocomplete="off"><button type="submit">Envoyer</button></div></form><button type="button" id="civi-help-resume">↩️ Continuer mon activité</button>';
doc.body.append(trigger,panel);const answer=doc.getElementById('civi-help-answer'),input=doc.getElementById('civi-help-input');
function toggle(value){open=value;panel.hidden=!value;trigger.setAttribute('aria-expanded',String(value));if(value)input.focus();else{root.NovaAudio?.stop();doc.getElementById('user-input')?.focus();}}
trigger.onclick=()=>toggle(!open);doc.getElementById('civi-help-close').onclick=()=>toggle(false);doc.getElementById('civi-help-resume').onclick=()=>toggle(false);
function paragraph(value){const p=doc.createElement('p');const parts=String(value).split(/(\*\*[^*]+\*\*)/g);for(const part of parts){if(part.startsWith('**')&&part.endsWith('**')){const b=doc.createElement('strong');b.textContent=part.slice(2,-2);p.append(b);}else p.append(doc.createTextNode(part));}return p;}
function questionLike(value,assessment=false){const q=root.NovaQuestions.normalize(value);const cue=/\b(comment|combien|pourquoi|qu est ce|c est quoi|peux tu|pouvez vous|ou retrouver|ou voir|ou consulter|je ne comprends|aide moi|aidez moi)\b/.test(q);if(assessment)return cue||/\?$/.test(value.trim());return cue||!!root.NovaQuestions.resolve(value);}
function getReply(value){const route=root.NovaQuestions.resolve(value),row=bank.get(route);return row||{answer:'Je n’ai pas identifié avec suffisamment de précision ce que vous cherchez. Reformulez en nommant le sujet : le prix de l’examen, vos résultats, une notion du cours ou une démarche. Vous pouvez aussi consulter le glossaire ou la FAQ.',links:[['📖 Consulter le glossaire','SCR_GLO_MENU'],['❔ Consulter la FAQ','SCR_FAQ_MENU']]};}
function ask(value,remote=false){value=String(value||'').trim();if(!value)return;if(!remote)root.NovaResume?.markLocal();lastQuestion=value;root.NovaTyping?.finish();toggle(true);input.value='';root.NovaAudio?.stop();const run=++replyToken;answer.replaceChildren(paragraph('Vous : '+value));const waiting=paragraph('Réponse en cours de chargement…');waiting.className='civi-help-waiting';waiting.setAttribute('role','status');answer.append(waiting);root.setTimeout(()=>{if(run!==replyToken)return;waiting.remove();const row=getReply(value);for(const part of row.answer.split(/\n+/).filter(Boolean))answer.append(paragraph(part));const links=doc.createElement('div');links.className='civi-help-links';for(const [label,target] of row.links||[]){if(/^SCR_QL_/.test(target)&&!/GLO/.test(target))continue;if(!/^[A-Z0-9_]+$/.test(target))continue;const a=doc.createElement('button');a.type='button';a.textContent=label;a.onclick=()=>{toggle(false);if(root.NovaRuntime?.navigate){root.NovaRuntime.navigate(target);return;}const link=doc.createElement('a');link.href='#'+root.btoa(target);doc.getElementById('chat').append(link);link.click();link.remove();};links.append(a);}answer.append(links);root.NovaAccess?.icons(answer);if(root.NovaAccess?.settings().audio)root.NovaAudio?.speak(root.NovaAudio.content(answer),answer);if(!remote)root.NovaResume?.captureLive();},180);}
doc.getElementById('civi-help-form').addEventListener('submit',event=>{event.preventDefault();event.stopPropagation();ask(input.value);});panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();toggle(false);}else if(event.key==='Enter'&&!event.shiftKey&&event.target===input){event.preventDefault();event.stopImmediatePropagation();ask(input.value);}},true);
function intercept(event){const native=doc.getElementById('user-input'),value=native?.textContent?.trim();if(!value)return;const node=[...doc.querySelectorAll('#chat .bot-message')].at(-1);if(node?.querySelector('.nova-question-input,.nova-question-answer')&&root.NovaRuntime?.askNative){event.preventDefault();event.stopImmediatePropagation();root.NovaQuestion?.begin();native.textContent='';root.NovaRuntime.askNative(value);return;}const assessment=!!node?.querySelector('[data-civi-question]')||/question\s+\d+|votre réponse/i.test(node?.textContent||'');if(!questionLike(value,assessment))return;event.preventDefault();event.stopImmediatePropagation();native.textContent='';ask(value);}
doc.addEventListener('click',event=>{if(event.target.closest?.('#send-button'))intercept(event);},true);doc.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.ctrlKey&&!event.altKey&&event.target===doc.getElementById('user-input'))intercept(event);},true);
root.NovaHelp={ask,getReply,questionLike,exportSession:()=>({open,question:lastQuestion}),importSession:s=>{if(!s)return;if(s.open&&s.question)ask(s.question,true);else toggle(false);}};
})(window);
