'use strict';
(function(root){
const doc=root.document,bank=new Map((root.CiviQuestionsBank||[]).map(row=>[row.id,row]));let suspended=null,lastQuestion='',serial=0;
const clone=v=>JSON.parse(JSON.stringify(v));
function paragraph(value){const heading=/^#{1,3}\s/.test(value);const p=doc.createElement(heading?'h3':'p');value=String(value).replace(/^#{1,3}\s/,'');for(const part of String(value).split(/(\*\*[^*]+\*\*)/g)){if(part.startsWith('**')&&part.endsWith('**')){const b=doc.createElement('strong');b.textContent=part.slice(2,-2);p.append(b);}else p.append(doc.createTextNode(part));}return p;}
function questionLike(value,assessment=false){const q=root.NovaQuestions.normalize(value);const cue=/\b(comment|combien|pourquoi|qu est ce|c est quoi|peux tu|pouvez vous|ou retrouver|ou voir|ou consulter|par quoi commencer|ou commencer|je veux|je souhaite|je voudrais|je ne comprends|aide moi|aidez moi)\b/.test(q);if(assessment)return cue||/\?$/.test(value.trim());return cue||/\?$/.test(value.trim())||!!root.NovaQuestions.resolve(value);}
function getReply(value){return bank.get(root.NovaQuestions.resolve(value))||{answer:'Je n’ai pas identifié avec suffisamment de précision ce que vous cherchez. Précisez le sujet : le prix de l’examen, vos résultats, une notion du cours ou une démarche.',links:[['📖 Consulter le glossaire','SCR_GLO_MENU'],['❔ Consulter la FAQ','SCR_FAQ_MENU']]};}
function activeNode(){return [...doc.querySelectorAll('#chat .bot-message')].filter(n=>!n.hasAttribute('data-civi-help')).at(-1);}
function remember(){if(suspended)return;const node=activeNode();if(!node)return;const activity=!!node.querySelector('iframe,[data-civi-question],.nova-feedback,.civi-revision-history')||/question\s+\d+|votre réponse|activité|exercice/i.test(node.textContent);if(!node.id)node.id='civi-activity-'+Date.now()+'-'+(++serial);suspended={activity:activity&&!/Que souhaitez-vous faire/.test(node.textContent),nodeId:node.id,html:node.outerHTML,runtime:clone(root.NovaRuntime.exportSession()),variables:clone(root.NovaSave.exportData().variables),controlsHidden:doc.body.classList.contains('hideControls')};}
function ask(value){value=String(value||'').trim();if(!value)return;root.NovaResume?.markLocal();root.NovaTyping?.finish();root.NovaAudio?.stop();remember();lastQuestion=value;const chat=doc.getElementById('chat'),user=doc.createElement('div');user.className='message user-message';user.textContent=value;user.id='civi-help-user-'+Date.now()+'-'+(++serial);chat.append(user);const answer=doc.createElement('div');answer.className='message bot-message';answer.dataset.civiHelp='true';answer.id='civi-help-reply-'+Date.now()+'-'+(++serial);answer.setAttribute('aria-live','polite');const row=getReply(value);let list=null;for(const part of row.answer.split(/\n+/).filter(Boolean)){if(/^[-*] /.test(part)){if(!list){list=doc.createElement('ul');answer.append(list);}const item=doc.createElement('li');item.append(paragraph(part.slice(2)));list.append(item);}else{list=null;answer.append(paragraph(part));}}const links=doc.createElement('div');links.className='civi-inline-help-links';for(const [label,target] of row.links||[]){if(!/^[A-Z0-9_]+$/.test(target)||/^SCR_QL_(AGAIN|RESET|INPUT)/.test(target))continue;const button=doc.createElement('button');button.type='button';button.textContent=label;button.dataset.civiHelpTarget=target;links.append(button);}answer.append(links);if(suspended){const resume=doc.createElement('button');resume.type='button';resume.className='civi-inline-resume';resume.dataset.civiHelpResume='true';resume.textContent=suspended.activity?'↩️ Reprendre mon activité':'↩️ Revenir au chatbot';answer.append(resume);}chat.append(answer);doc.body.classList.remove('hideControls');root.NovaBoot?.rendered(answer);root.NovaAccess?.icons(answer);answer.scrollIntoView({block:'start',behavior:root.NovaAccess?.settings().motion?'auto':'smooth'});if(root.NovaAccess?.settings().audio)root.NovaAudio?.speak(root.NovaAudio.content(answer),answer);root.NovaResume?.captureLive();}
function resume(){if(!suspended)return;root.NovaResume?.markLocal();root.NovaTyping?.finish();root.NovaAudio?.stop();const saved=suspended;let node=doc.getElementById(saved.nodeId);if(!node){const parsed=new DOMParser().parseFromString(saved.html,'text/html');node=parsed.body.firstElementChild;if(!node)return;for(const el of node.querySelectorAll('script,object,embed'))el.remove();for(const el of [node,...node.querySelectorAll('*')])for(const a of [...el.attributes])if(/^on/i.test(a.name)||a.name==='srcdoc')el.removeAttribute(a.name);doc.getElementById('chat').append(node);}if(saved.variables&&JSON.stringify(saved.variables)!==JSON.stringify(root.NovaSave.exportData().variables))root.NovaSave.importData({...root.NovaSave.exportData(),variables:saved.variables},true);root.NovaRuntime.importSession(saved.runtime);doc.body.classList.toggle('hideControls',saved.controlsHidden);suspended=null;for(const button of doc.querySelectorAll('[data-civi-help-resume]')){button.disabled=true;button.textContent=saved.activity?'✓ Activité reprise':'✓ Retour au chatbot';}node.scrollIntoView({block:'start',behavior:'auto'});doc.getElementById('user-input')?.focus({preventScroll:true});root.NovaResume?.captureLive();}
doc.addEventListener('click',event=>{if(event.target.closest?.('#chat a'))suspended=null;const target=event.target.closest?.('[data-civi-help-target],[data-civi-help-resume]');if(!target)return;event.preventDefault();event.stopImmediatePropagation();if(target.hasAttribute('data-civi-help-resume'))resume();else{root.NovaResume?.markLocal();root.NovaRuntime.navigate(target.dataset.civiHelpTarget);}},true);
function intercept(event){const native=doc.getElementById('user-input'),value=native?.textContent?.trim();if(!value)return;const node=activeNode();const assessment=!!node?.querySelector('[data-civi-question]')||/question\s+\d+|votre réponse/i.test(node?.textContent||'');if(!questionLike(value,assessment)&&!node?.querySelector('.nova-question-input,.nova-question-answer'))return;event.preventDefault();event.stopImmediatePropagation();native.textContent='';ask(value);}
doc.addEventListener('click',event=>{if(event.target.closest?.('#send-button'))intercept(event);},true);doc.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.ctrlKey&&!event.altKey&&event.target===doc.getElementById('user-input'))intercept(event);},true);
root.NovaHelp={ask,getReply,questionLike,resume,exportSession:()=>({inline:true,question:lastQuestion,suspended:suspended?clone(suspended):null}),importSession:s=>{lastQuestion=s?.question||'';suspended=s?.inline&&s.suspended?clone(s.suspended):null;}};
})(window);
