'use strict';
(function(root){
const KEY='novafrate-civique-v14';let state={version:14,variables:{},history:{bilan:[],entrainement:[],examen:[]}},bound=null,restored=false,enabled=true;
const clone=x=>JSON.parse(JSON.stringify(x));
function valid(x){return x&&x.version===14&&x.variables&&typeof x.variables==='object'&&!Array.isArray(x.variables)&&x.history&&['bilan','entrainement','examen'].every(k=>Array.isArray(x.history[k])&&x.history[k].length<=20)&&JSON.stringify(x).length<2000000;}
try{const saved=JSON.parse(root.localStorage.getItem(KEY)||'null');if(valid(saved))state=saved;}catch(e){enabled=false;}
function notice(s){const n=root.document&&root.document.getElementById('save-status');if(n)n.textContent=s;}
function write(){state.updated=new Date().toISOString();try{root.localStorage.setItem(KEY,JSON.stringify(state));notice('Progression sauvegardée sur ce navigateur.');}catch(e){enabled=false;notice('Sauvegarde indisponible : exportez votre parcours pour le conserver.');}}
const groups={bilan:{prefix:/^parcours/,flag:'parcoursDisponible',run:'parcoursRun',score:'parcoursScore',max:25},entrainement:{prefix:/^train/,flag:'trainDisponible',run:'trainRun',score:'trainScore',max:10},examen:{prefix:/^last/,flag:'lastExamDisponible',run:'lastSavedRun',score:'lastExamScore',max:40}};
function capture(v){for(const [kind,g] of Object.entries(groups)){if(!v[g.flag])continue;const signature=String(v[g.run]);const rows=state.history[kind];if(rows.some(r=>r.run===signature))continue;const vars=Object.fromEntries(Object.entries(v).filter(([k])=>g.prefix.test(k)));const max=kind==='entrainement'?Object.keys(v).filter(k=>/^trainTotal[1-5]$/.test(k)).reduce((a,k)=>a+Number(v[k]||0),0)||10:g.max;rows.unshift({run:signature,date:new Date().toISOString(),score:Number(v[g.score]||0),max,variables:clone(vars)});rows.splice(20);}}
function before(v){if(!v||typeof v!=="object")return;if(!restored){Object.assign(v,clone(state.variables));restored=true;}bound=v;try{for(let t=1;t<=5;t++)for(let c=1;c<=6;c++){const key='SCR_REV_T'+t+'_CH'+String(c).padStart(2,'0');if(root.localStorage.getItem('nova-activity-'+key)==='true')v['activite_'+key]=true;}}catch(e){} }
function after(v){if(!v||typeof v!=="object")return;bound=v;capture(v);state.variables=clone(v);delete state.variables.qlQuestion;delete state.variables.INPUT;write();}
function restore(kind,i){const row=state.history[kind]&&state.history[kind][i];if(!row)return;Object.assign(state.variables,clone(row.variables));if(bound)Object.assign(bound,clone(row.variables));write();navigate('SCR_PARCOURS_MENU');}
function navigate(target){if(!root.document)return;const a=root.document.createElement('a');a.href='#'+root.btoa(target);a.textContent='Mon parcours';const chat=root.document.getElementById('chat');chat.append(a);a.click();a.remove();}
function history(){const host=root.document.getElementById('saved-list');host.replaceChildren();for(const [kind,label] of [['bilan','Bilans'],['entrainement','Entraînements'],['examen','Examens blancs']]){const h=root.document.createElement('h3');h.textContent=label;host.append(h);if(!state.history[kind].length){const p=root.document.createElement('p');p.textContent='Aucun résultat enregistré.';host.append(p);}state.history[kind].forEach((row,i)=>{const b=root.document.createElement('button');b.textContent=new Date(row.date).toLocaleString('fr-FR')+' — '+row.score+'/'+row.max;b.onclick=()=>{restore(kind,i);root.document.getElementById('saved-panel').hidden=true;};host.append(b);});}}
function importData(x){if(!valid(x))throw Error('Fichier de parcours invalide.');for(const [k,v] of Object.entries(x.variables)){if(!/^[a-zA-Z0-9_]+$/.test(k)||['__proto__','constructor','prototype'].includes(k)||!['string','number','boolean'].includes(typeof v))throw Error('Variables invalides.');}for(const [kind,rows] of Object.entries(x.history)){if(!groups[kind])throw Error('Historique invalide.');for(const row of rows){if(!row.variables||typeof row.variables!=='object')throw Error('Résultat invalide.');for(const [k,v] of Object.entries(row.variables))if(!groups[kind].prefix.test(k)||!/^[a-zA-Z0-9_]+$/.test(k)||!['string','number','boolean'].includes(typeof v))throw Error('Résultat invalide.');}}state=clone(x);if(bound)Object.assign(bound,state.variables);write();}
root.NovaSave={before,after,restore,importData,exportData:()=>clone(state),history};
if(root.addEventListener)root.addEventListener('message',event=>{if(event.origin!==root.location.origin||!event.data||event.data.source!=='nova-activity')return;const frames=[...root.document.querySelectorAll('iframe')];if(!frames.some(f=>f.contentWindow===event.source))return;const key=event.data.chapter;if(!/^SCR_REV_T[1-5]_CH\d{2}$/.test(key))return;if(event.data.requestProgress===true){event.source.postMessage({source:'nova-progress',chapter:key,complete:state.variables['activite_'+key]===true&&state.variables['activiteVersion_'+key]===15},event.origin);return;}if(event.data.navigate===key+'_GLO'||event.data.navigate===key+'_COURS'){navigate(event.data.navigate);return;}if(event.data.quizComplete===true){const score=Number(event.data.score),total=Number(event.data.total);if(!Number.isInteger(score)||!Number.isInteger(total)||score<0||total<1||total>10||score>total)return;state.variables['revisionScore_'+key]=score;state.variables['revisionTotal_'+key]=total;if(bound){bound['revisionScore_'+key]=score;bound['revisionTotal_'+key]=total;}write();return;}if(event.data.complete!==true)return;const fresh=!state.variables['activite_'+key];state.variables['activite_'+key]=true;if(event.data.version===15)state.variables['activiteVersion_'+key]=15;if(bound){bound['activite_'+key]=true;if(event.data.version===15)bound['activiteVersion_'+key]=15;}write();notice('Deux activités terminées : les questions de connaissances sont disponibles.');});
if(root.document){root.document.getElementById('saved-toggle').onclick=()=>{const p=root.document.getElementById('saved-panel');p.hidden=!p.hidden;history();};root.document.getElementById('export').onclick=()=>{const a=root.document.createElement('a');const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=u;a.download='mon-parcours-civique.json';a.click();URL.revokeObjectURL(u);};root.document.getElementById('import').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>2000000)throw Error('Fichier trop volumineux.');importData(JSON.parse(await file.text()));root.location.reload();}catch(err){notice(err.message);}e.target.value='';};root.document.getElementById('erase').onclick=()=>{if(!root.confirm('Effacer tous vos résultats sauvegardés sur ce navigateur ?'))return;root.localStorage.removeItem(KEY);for(let t=1;t<=5;t++)for(let c=1;c<=6;c++){const chapter='SCR_REV_T'+t+'_CH'+String(c).padStart(2,'0');root.localStorage.removeItem('nova-activity-'+chapter);root.localStorage.removeItem('nova-ateliers-v15-'+chapter);}root.localStorage.removeItem('nova-geo-completed');root.location.reload();};}
})(typeof window!=='undefined'?window:globalThis);
