const {JSDOM}=require(process.env.CIVICOACH_JSDOM_PATH||'jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');const pause=n=>new Promise(r=>setTimeout(r,n));
async function start(saved=null){
 const html=fs.readFileSync(base+'/chatbot/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
 const dom=new JSDOM(html,{url:'http://localhost/chatbot/#http://localhost/chat_bot.md',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent},set(v){this.textContent=v}});
 w.localStorage.setItem('civicoach-accessibilite-v1',JSON.stringify({motion:true}));if(saved)w.localStorage.setItem('novafrate-civique-v14',JSON.stringify(saved));
 w.fetch=async url=>{const u=new URL(url,w.location.href),file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+'/'))throw Error('Unexpected URL');return new Response(fs.readFileSync(file),{status:200,headers:{'content-type':file.endsWith('.json')?'application/json':'text/plain'}});};w.speechSynthesis={cancel(){},getVoices:()=>[],speak(u){w.spoken=(w.spoken||[]).concat(u.text);setTimeout(()=>u.onend?.(),0);},pause(){},resume(){}};w.SpeechSynthesisUtterance=class{constructor(t){this.text=t}};
 for(const f of ['liaison.js','vendor/jspdf.umd.min.js','vendor/parcours-font.js','frate-brand.js','feedback-data.js','feedbacks.js','icones.js','parcours-pdf.js','tirages-data.js','tirages.js','demarrage.js','questions-banque.js','questions-moteur.js','sauvegarde.js','presentation.js','accessibilite.js','revision-parcours.js','questions-partout.js','lecture-audio.js','question-attente.js','chatmd.js'])w.eval(fs.readFileSync(base+'/chatbot/'+f,'utf8'));
 const deadline=Date.now()+45000;while(!w.NovaRuntime||!w.document.querySelector('#chat .bot-message .messageOptions')){if(Date.now()>deadline)throw Error('ChatMD did not start: '+errors.join(';'));await pause(100);}
 await pause(200);assert.equal(errors.length,0,errors.join(';'));return {dom,w,errors};
}
(async()=>{
const {dom,w,errors}=await start();const d=w.document;assert(d.querySelector('#chat').textContent.includes('Mon parcours personnalisé'));assert(d.querySelector('.civi-expand-callout strong'));
const original=JSON.stringify(w.NovaSave.exportData().variables);d.getElementById('user-input').textContent='Combien coûte l’examen ?';d.getElementById('send-button').click();await pause(500);assert(!d.getElementById('civi-help-panel').hidden);assert(/euros|€/.test(d.getElementById('civi-help-answer').textContent));assert.equal(JSON.stringify(w.NovaSave.exportData().variables),original,'help changed quiz state');
w.NovaHelp.ask('Comment retrouver mes résultats après ?');await pause(300);assert(d.getElementById('civi-help-answer').textContent.includes('Mon parcours personnalisé'));assert.equal(w.NovaQuestions.resolve('Comment vas-tu ?'),'INTENT_SOCIAL');
d.getElementById('a11y-audio').click();await pause(30);assert(w.NovaAccess.settings().audio);assert(w.spoken.length>0);d.getElementById('audio-stop').click();
w.NovaSave.before({});const v={trainDisponible:true,trainRun:99,trainScore:1,trainT1:1,trainTotal1:10,trainMistakes:''};w.NovaSave.before(v);const key=Object.keys(w.CiviFeedbackData.questions).find(k=>w.CiviFeedbackData.questions[k].notion==='Laïcité');w.NovaSave.recordMistake('entrainement',key,'Choix incorrect');v.trainMistakes='|'+key+'|';w.NovaSave.after(v);const saved=w.NovaSave.exportData();assert.equal(saved.history.entrainement.length,1);assert(JSON.parse(saved.history.entrainement[0].variables.trainFeedbackChoices)[key]);
const runtime=w.NovaRuntime.exportSession();w.NovaResume.captureLive();const snap=w.NovaSave.exportData().resume;assert(snap.runtime);const imported={...snap,updated:snap.updated+1,sequence:snap.sequence+1,html:snap.html+'<div class="message bot-message"><p>Conversation synchronisée</p></div>'};w.NovaResume.applyLive(imported);assert(d.getElementById('chat').textContent.includes('Conversation synchronisée'));assert.equal(JSON.stringify(w.NovaRuntime.exportSession().nextMessage),JSON.stringify(runtime.nextMessage));assert.equal(errors.length,0,errors.join(';'));
const newer=await start(saved);assert.equal(newer.w.NovaSave.exportData().history.entrainement[0].score,1);assert(newer.w.document.querySelector('#chat').textContent.includes('Mon parcours personnalisé'));assert.equal(errors.length,0,errors.join(';'));const b=newer.w;Object.defineProperty(b,'opener',{value:w,configurable:true});w.open=()=>b;w.postMessage=(packet,origin)=>w.dispatchEvent(new w.MessageEvent('message',{data:packet,origin,source:b}));b.postMessage=(packet,origin)=>b.dispatchEvent(new b.MessageEvent('message',{data:packet,origin,source:w}));w.NovaLink.open('http://localhost/chatbot/');w.dispatchEvent(new w.MessageEvent('message',{data:{source:'civicoach-companion-request'},origin:w.location.origin,source:b}));w.NovaHelp.ask('Combien coûte l’examen ?');await pause(800);assert(b.document.getElementById('civi-help-answer').textContent.includes('Combien coûte'),'Moodle to tab question not transmitted');b.NovaHelp.ask('Comment retrouver mes résultats après ?');await pause(800);assert(d.getElementById('civi-help-answer').textContent.includes('Comment retrouver'),'tab to Moodle question not transmitted');
d.getElementById('civi-help-close').click();await w.NovaRuntime.navigate('SCR_QL_INPUT');d.getElementById('user-input').textContent='Combien coûte l’examen ?';d.getElementById('send-button').click();await pause(800);assert(/euros|€/.test([...d.querySelectorAll('#chat .bot-message')].at(-1).textContent),'native question did not answer');await pause(600);assert(/euros|€/.test([...b.document.querySelectorAll('#chat .bot-message')].at(-1).textContent),'native question answer not synchronized');b.document.getElementById('user-input').textContent='Comment vas-tu ?';b.document.getElementById('send-button').click();await pause(800);assert([...d.querySelectorAll('#chat .bot-message')].at(-1).textContent.includes('prêt à vous accompagner'),'native question input not restored in synchronized window');
const beforeOld=d.getElementById('chat').textContent;w.NovaResume.applyLive(snap);assert.equal(d.getElementById('chat').textContent,beforeOld,'older snapshot replaced a newer interaction');await w.NovaRuntime.navigate('SCR_PARCOURS_REV_ACT_T4');await pause(300);assert(d.querySelector('.civi-revision-history .civi-revision-card'),'revision history not rendered');assert(d.querySelector('.civi-revision-history').textContent.includes('Patrimoine'));assert.equal(errors.length,0,errors.join(';'));assert.equal(newer.errors.length,0,newer.errors.join(';'));newer.dom.window.close();dom.window.close();console.log('PASS real ChatMD runtime: welcome, global question without state loss, audio controls, chosen mistake, reload persistence, live conversation/context import, bidirectional opener/peer synchronization, native question/answer and input restore, rejection of older snapshots, revision chapter menu');
})().catch(e=>{console.error(e);process.exit(1)});
