const {JSDOM}=require(process.env.CIVICOACH_JSDOM_PATH||'jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');const pause=n=>new Promise(r=>setTimeout(r,n));
async function start(saved=null){
 const html=fs.readFileSync(base+'/chatbot/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
 const dom=new JSDOM(html,{url:'http://localhost/chatbot/#http://localhost/chat_bot.md',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent},set(v){this.textContent=v}});
 w.localStorage.setItem('civicoach-accessibilite-v1',JSON.stringify({motion:true}));if(saved)w.localStorage.setItem('novafrate-civique-v14',JSON.stringify(saved));
 w.fetch=async url=>{const u=new URL(url,w.location.href),file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+'/'))throw Error('Unexpected URL');return new Response(fs.readFileSync(file),{status:200,headers:{'content-type':file.endsWith('.json')?'application/json':'text/plain'}});};w.speechSynthesis={cancel(){},getVoices:()=>[],speak(u){w.spoken=(w.spoken||[]).concat(u.text);setTimeout(()=>u.onend?.(),0);},pause(){},resume(){}};w.SpeechSynthesisUtterance=class{constructor(t){this.text=t}};
 for(const f of [...fs.readFileSync(base+'/chatbot/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1].split('?')[0]).concat('chatmd.js'))w.eval(fs.readFileSync(base+'/chatbot/'+f,'utf8'));
 const deadline=Date.now()+45000;while(!w.NovaRuntime||!w.document.querySelector('#chat .bot-message .messageOptions')){if(Date.now()>deadline)throw Error('ChatMD did not start: '+errors.join(';'));await pause(100);}
 await pause(200);assert.equal(errors.length,0,errors.join(';'));return {dom,w,errors};
}
(async()=>{const {dom,w}=await start();let st=w.NovaSave.exportData();st.variables={...st.variables,bilExam:'NAT',bilRun:1,score:19,score_t1:4,score_t2:4,score_t3:4,score_t4:4,score_t5:3};w.NovaSave.importData(st,true);await w.NovaRuntime.navigate('BIL_NAT_DEC_V01_RESULT');await pause(200);assert.equal(w.NovaSave.exportData().history.bilan[0].score,19);await w.NovaRuntime.navigate('SCR_BIL_PROG_EXAMEN');await pause(200);const links=[...w.document.querySelectorAll('#chat .bot-message')].at(-1).querySelectorAll('a');[...links].find(a=>a.textContent.includes('Naturalisation')).click();await pause(300);assert.equal([...w.document.querySelectorAll('#score_precedent')].at(-1).value,'19');const current=w.NovaSave.exportData();assert.equal(w.NovaPriorBilan.previous('NAT',{variables:current.variables,history:{bilan:[]}}).score,19);assert.equal(w.NovaPriorBilan.previous('CR',{variables:current.variables,history:{bilan:[]}}),null);const chat=w.document.getElementById('chat');chat.innerHTML=chat.innerHTML;await pause(100);assert.equal([...w.document.querySelectorAll('#score_precedent')].at(-1).value,'19');assert.equal(w.document.querySelectorAll('.civi-feedback a').length,0);console.log('PASS real bilan result to progression via exam choice, legacy saved result fallback, restored chat prefill, text-only chapter advice');dom.window.close()})().catch(e=>{console.error(e);process.exit(1)});