const {JSDOM}=require(process.env.CIVICOACH_JSDOM_PATH||'jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');const pause=n=>new Promise(r=>setTimeout(r,n));
async function start(saved=null){
 const html=fs.readFileSync(base+'/chatbot/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
 const dom=new JSDOM(html,{url:'http://localhost/chatbot/#http://localhost/chat_bot.md',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent},set(v){this.textContent=v}});
 w.localStorage.setItem('civicoach-accessibilite-v1',JSON.stringify({motion:true}));if(saved)w.localStorage.setItem('novafrate-civique-v14',JSON.stringify(saved));
 w.fetch=async url=>{const u=new URL(url,w.location.href),file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+'/'))throw Error('Unexpected URL');return new Response(fs.readFileSync(file),{status:200,headers:{'content-type':file.endsWith('.json')?'application/json':'text/plain'}});};w.speechSynthesis={cancel(){},getVoices:()=>[],speak(u){w.spoken=(w.spoken||[]).concat(u.text);setTimeout(()=>u.onend?.(),0);},pause(){},resume(){}};w.SpeechSynthesisUtterance=class{constructor(t){this.text=t}};
 for(const f of [...fs.readFileSync(base+'/chatbot/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1].split('?')[0]).concat('chatmd.js'))w.eval(fs.readFileSync(base+'/chatbot/'+f,'utf8'));
 const deadline=Date.now()+45000;while(!w.NovaRuntime||!w.document.querySelector('#chat .bot-message .messageOptions')){if(Date.now()>deadline)throw Error('ChatMD did not start: '+errors.join(';'));await pause(100);}
 await pause(200);assert.equal(errors.length,0,errors.join(';'));return {dom,w,errors};
}
(async()=>{const {dom,w}=await start();const d=w.document;for(const [variables,label] of [[{},'Démarrer les activités'],[{atelier_SCR_REV_T1_CH01:JSON.stringify({step:1,complete:false,score:1,total:2})},'Continuer les activités'],[{activite_SCR_REV_T1_CH01:true},'Revoir les activités']]){w.NovaSave.importData({...w.NovaSave.exportData(),variables},true);const host=d.createElement('div');host.innerHTML='<div class="civi-revision-history" data-theme="1" data-mode="act"></div>';d.getElementById('chat').append(host);await w.NovaRevisions.render(host);const link=host.querySelector('a');assert(link.textContent.includes(label));assert.equal(w.atob(link.hash.slice(1)),'SCR_REV_T1_CH01_ACT');link.click();await pause(200);const last=[...d.querySelectorAll('#chat .bot-message')].at(-1);assert(last.querySelector('iframe[src*="chapitre=SCR_REV_T1_CH01"]'));assert(!last.textContent.includes('Notions utiles'));host.remove();}dom.window.close();console.log('PASS accès direct aux activités : nouvelle, en cours, terminée ; écran iframe sans détour par les notions');})().catch(e=>{console.error(e);process.exit(1)});