const {chromium}=require(process.env.NOVA_PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
(async()=>{
 const base=path.resolve(__dirname,'..'),output=path.join(base,'.build_ui');fs.mkdirSync(output,{recursive:true});
 const data=JSON.parse(fs.readFileSync(base+'/activites-revision/data.json'));let origin;
 const server=http.createServer((req,res)=>{let p=path.join(base,decodeURIComponent(new URL(req.url,origin).pathname));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.md':'text/plain','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:740,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function open(k,st=0){await page.goto(origin+'/activites-revision/?chapitre='+k);await page.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);await page.evaluate(n=>{step=n;render();},st);assert(await page.locator('#questions').isEnabled());}


 await page.route('**/test-frame',r=>r.fulfill({contentType:'text/html',body:'<iframe style="width:740px;height:1300px" src="'+origin+'/activites-revision/?chapitre=SCR_REV_T4_CH03"></iframe>'}));
 await page.goto(origin+'/test-frame');const frame=page.frames().find(f=>f.url().includes('activites-revision'));await frame.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);
 for(let i=0;i<4;i++){const q=await frame.evaluate(()=>lesson.activities[step].items[order[qi]]);await frame.getByRole('button',{name:'Découvrir sans gratter (clavier)',exact:true}).click();await frame.getByRole('button',{name:q.answer,exact:true}).click();await frame.locator('#next').click();}
 assert.equal(await frame.evaluate(()=>step),1);assert.equal(await frame.locator('[data-card]').count(),1);
 const popupPromise=page.waitForEvent('popup');await frame.locator('#open-large').click();const popup=await popupPromise;await popup.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);assert.equal(await popup.evaluate(()=>step),1);assert.equal(await popup.evaluate(()=>score),4);assert.equal(await popup.locator('[data-card]').count(),1);
 const first=await popup.evaluate(()=>lesson.activities[step].items[order[qi]]);await popup.locator('[data-card]').click();await popup.locator('[data-target="'+first.target+'"]').first().click();assert.equal(await popup.evaluate(()=>qi),1);assert(await popup.locator('#next').isHidden());await frame.waitForFunction(()=>qi===1,null,{timeout:5000});
 assert.equal(await popup.locator('.overseas [data-target]').count(),5);await popup.locator('#activity').screenshot({path:path.join(output,'specialites-v21.png')});await popup.setViewportSize({width:390,height:844});assert(await popup.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await popup.setViewportSize({width:740,height:950});
 await popup.reload();await popup.waitForFunction(()=>typeof lesson!=='undefined'&&lesson);assert.equal(await popup.evaluate(()=>qi),1);
 const q=await popup.evaluate(()=>lesson.activities[step].items[order[qi]]);await popup.locator('[data-card]').click();await popup.evaluate(target=>[...document.querySelectorAll('[data-target]')].find(b=>b.dataset.target!==target).dispatchEvent(new MouseEvent('click',{bubbles:true})),q.target);assert.equal(await popup.evaluate(()=>qi),1);
 for(let i=1;i<18;i++){const q=await popup.evaluate(()=>lesson.activities[step].items[order[qi]]);await popup.locator('[data-card]').click();await popup.locator('[data-target="'+q.target+'"]').first().click();assert.equal(await popup.evaluate(()=>qi),i+1);}
 assert(await popup.evaluate(()=>stageReady));await popup.locator('#next').click();assert.equal(await popup.evaluate(()=>step),2);await frame.waitForFunction(()=>step===2,null,{timeout:5000});console.log('OK ouverture à l’activité 2, reprise des spécialités, progression automatique, 5 territoires ultramarins et synchronisation retour.');
 await page.route('**/chat_bot.md',r=>r.fulfill({body:fs.readFileSync(base+'/chat_bot.md','utf8').replaceAll('https://codeurfou-sys.github.io/chatbot_civique2/',origin+'/'),contentType:'text/plain'}));
 await page.goto(origin+'/chatbot/');await page.waitForTimeout(7000);assert.equal(await page.locator('#chatbot-name').innerText(),'CiviCoach');assert(!(await page.locator('#saved-toggle').isVisible()));assert.equal(await page.locator('header .nova-open-large').count(),0);assert(!(await page.locator('.nova-large-link').first().isVisible()));
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(output,'accueil-v21.png')});await page.evaluate(()=>{const x=NovaSave.exportData();x.history.bilan=[{date:'2026-10-07T09:00:00Z',score:18,max:25,variables:{parcoursScore:18,parcoursDisponible:true,parcoursRun:'sample',parcoursExam:'CR'}}];x.variables.atelier_SCR_REV_T4_CH03=JSON.stringify({version:19,step:1,score:4,total:4,updated:Date.now()});NovaSave.importData(x);const a=document.createElement('a');a.href='#'+btoa('SCR_REV_T4_CH03_ACT');document.querySelector('#chat').append(a);a.click();a.remove();});await page.waitForTimeout(3500);
 const nativeFrame=page.frames().find(f=>f.url().includes('activites-revision'));await nativeFrame.waitForFunction(()=>step===1,null,{timeout:10000});await page.evaluate(()=>{const a=document.createElement('a');a.href='#'+btoa('SCR_SAVE_MENU');document.querySelector('#chat').append(a);a.click();a.remove();});await page.waitForTimeout(2000);const resultsPromise=page.waitForEvent('popup');await page.locator('.nova-open-saved').last().click();const results=await resultsPromise;await results.waitForFunction(()=>typeof NovaSave!=='undefined'&&document.querySelector('#saved-list').textContent.includes('18/25'));assert(await results.locator('#saved-panel').isVisible());assert(!(await results.locator('#chat').isVisible()));
 const dlPromise=results.waitForEvent('download');await results.locator('#export-pdf').click();const dl=await dlPromise;await dl.saveAs(path.join(output,'parcours-v21.pdf'));await page.screenshot({path:path.join(output,'civicoach-v21.png')});await results.screenshot({path:path.join(output,'resultats-v21.png')});console.log('OK nom CiviCoach, accueil sans doublons, résultats ouverts directement et export PDF.');
 assert.deepEqual(errors,[]);await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
