const {JSDOM}=require(process.env.CIVICOACH_JSDOM_PATH||'jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');const pause=n=>new Promise(r=>setTimeout(r,n));
async function start(saved=null){
 const html=fs.readFileSync(base+'/chatbot/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
 const dom=new JSDOM(html,{url:'http://localhost/chatbot/#http://localhost/chat_bot.md',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent},set(v){this.textContent=v}});
 w.localStorage.setItem('civicoach-accessibilite-v1',JSON.stringify({motion:true}));if(saved)w.localStorage.setItem('novafrate-civique-v14',JSON.stringify(saved));
 w.fetch=async url=>{const u=new URL(url,w.location.href),file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+'/'))throw Error('Unexpected URL');return new Response(fs.readFileSync(file),{status:200,headers:{'content-type':file.endsWith('.json')?'application/json':'text/plain'}});};w.speechSynthesis={cancel(){},getVoices:()=>[],speak(u){w.spoken=(w.spoken||[]).concat(u.text);setTimeout(()=>u.onend?.(),0);},pause(){},resume(){}};w.SpeechSynthesisUtterance=class{constructor(t){this.text=t}};
 for(const f of [...fs.readFileSync(base+'/chatbot/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1].split('?')[0]).concat('chatmd.js'))w.eval(fs.readFileSync(base+'/chatbot/'+f,'utf8'));
 const deadline=Date.now()+45000;while(!w.NovaRuntime||!w.document.querySelector('#chat .bot-message .messageOptions')){if(Date.now()>deadline)throw Error('ChatMD did not start: '+errors.join(';'));await pause(100);}
 await pause(200);assert.equal(errors.length,0,errors.join(';'));return {dom,w,errors};
}
(async()=>{const {dom,w}=await start();const d=w.document;await w.NovaRuntime.navigate('SCR_REV_T1_CH01_ACT');await pause(100);const state=JSON.stringify(w.NovaSave.exportData().variables);const opened=[];w.NovaLink.open=url=>opened.push(url);d.getElementById('civi-open-full').click();assert.equal(opened.length,1);assert(new URL(opened[0]).searchParams.get('reprendre')==='1');assert.equal(new URL(opened[0]).hash,w.location.hash);assert.equal(JSON.stringify(w.NovaSave.exportData().variables),state);assert(w.NovaSave.exportData().resume.html.includes('chapitre=SCR_REV_T1_CH01'));assert(d.getElementById('civi-open-full').getAttribute('aria-label').includes('nouvel onglet'));dom.window.close();console.log('PASS bouton grand écran : transfert existant, URL de reprise, activité et variables conservées');})().catch(e=>{console.error(e);process.exit(1)});