const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(process.argv[2] || 'chatmd_runtime.js','utf8');const ctx={console};vm.createContext(ctx);
const search=source.slice(source.indexOf('function St('),source.indexOf('function Ht('));
const conversion=source.slice(source.indexOf('function Ye('),source.indexOf('function Qe('));
const cond=source.slice(source.indexOf('function Zn('),source.indexOf('const Xn='));
const declarations=source.slice(source.indexOf('const Xn='),source.indexOf('function cr('));
const rendering=source.slice(source.indexOf('function cr('),source.indexOf('function mr('));
vm.runInContext('const e={secureMode:false};function _t(a){return a[0]}'+conversion+search+cond+declarations+rendering+';globalThis.render=hr;globalThis.nativeEval=lr;',ctx);
function sections(path){const text=fs.readFileSync(path,'utf8');return Object.fromEntries([...text.matchAll(/^## (\w+)\s*\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm)].map(x=>[x[1],x[2]]))}
function parse(body){const stack=[],choices=[],lines=[];for(const line of body.split('\n')){if(line.startsWith('`if '))stack.push(line.slice(4,-1));if(line==='`endif`')stack.pop();const opt=line.match(/^\d+\. \[(.+)\]\(([^)]+)\)$/);if(opt)choices.push({label:opt[1],target:opt[2],cond:stack.map(s=>'('+s+')').join(' && ')});else lines.push(line)}return lines.join('\n')+'\n<ul>'+choices.map(c=>(c.cond?'\n`if '+c.cond+'`\n':'')+'<li><a href="#'+c.target+'">'+c.label+'</a></li>'+(c.cond?'\n`endif`\n':'')).join('')+'</ul>'}
const glo=sections('modules/04_glossaire.md');const entries=JSON.parse(fs.readFileSync('data/glossaire_v6.json','utf8'));
for(const [query,title] of [['SMIC','SMIC'],['smic','SMIC'],['smik','SMIC'],['laicite','Laïcité'],['LAÏCITÉ','Laïcité'],['gouvernment','Gouvernement'],['gouvernement','Gouvernement'],['democratie','Démocratie'],['democartie','Démocratie'],['cotisation','Cotisations sociales']]){const vars={gloQuery:query};let out=ctx.render(parse(glo.SCR_GLO_SEARCH_RESULT),vars);const target=entries.find(e=>e.title===title).id;if(!out.includes('href="#'+target+'"'))console.log('Diagnostic',query,vars.gloBest,vars['gloScore'+target.slice(-4)]);assert(out.includes('href="#'+target+'"'),query+' : '+out.slice(-800));assert(!out.includes('Je n’ai pas trouvé'),query);console.log('Recherche native :',query,'→',title)}
for(const prefix of ['','a','ab','abs','abstention','s','sm','smic','zz']){const vars={gloPrefix:prefix},out=ctx.render(parse(glo.SCR_GLO_FILTER),vars);for(const letter of 'abcdefghijklmnopqrstuvwxyz'){const possible=entries.some(e=>e.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().startsWith(prefix+letter));assert.strictEqual(vars['gloNext'+letter.toUpperCase()],possible,'filtre '+prefix+letter);const id=Buffer.from('SCR_GLO_FILTER_NEXT_'+letter.toUpperCase()).toString('base64');assert.strictEqual(out.includes('href="#'+id+'"'),possible,'lettre '+letter)}for(const e of entries){const match=prefix!==''&&e.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().startsWith(prefix);assert.strictEqual(out.includes('href="#'+e.id+'"'),match,'résultats '+prefix+' '+e.title)}}
let vars={gloPrefix:'abs'};ctx.render(glo.SCR_GLO_FILTER_BACK,vars);assert.strictEqual(vars.gloPrefix,'ab');ctx.render(glo.SCR_GLO_FILTER_RESET,vars);assert.strictEqual(vars.gloPrefix,'');console.log('Filtre : alphabet complet, lettres actives/grisées, résultats et retours vérifiés.');
const rev=sections('modules/03_revisions.md');for(const [q,kind] of [['le salaire, les congés payés, les contributions de l’employeur','partielle'],['salaire','partielle'],['salaire BRUT salaire NET COTISATIONS','Bonne réponse'],['BRUT NET CONTRIBUTIONS','Bonne réponse'],['une bicyclette','Mauvaise réponse']]){const out=ctx.render(parse(rev.SCR_REV_T5_CH03_VERIF_Q02_RESULT),{rep_t5_ch3_q2:q});assert(out.includes(kind),q);assert.strictEqual(['Bonne réponse','Réponse partielle','Mauvaise réponse'].filter(t=>out.includes(t)).length,1,q);console.log('Révision bulletin de salaire :',q,'→',kind)}
const bil=sections('modules/02_bilan.md');for(const scores of [[0,2,3,4,5],[5,4,3,2,0],[5,5,5,5,5],[0,0,0,0,0]]){const vars=Object.fromEntries(scores.map((x,i)=>['score_t'+(i+1),x]));const out=ctx.render(parse(bil.BIL_CSP_DEC_V01_RECO),vars);const priorities=[...out.matchAll(/— priorité (très haute|haute|moyenne|faible)/g)].map(m=>['très haute','haute','moyenne','faible'].indexOf(m[1]));assert.strictEqual(priorities.length,5);assert.deepStrictEqual(priorities,[...priorities].sort());assert(out.includes('SCR_ENT_CSP_T1_Q_LAUNCH'));}
let scoreVars={score:0,score_t1:0,score_t2:0,score_t3:0,score_t4:0,score_t5:0};for(let n=1;n<=25;n++)ctx.render(parse(bil['BIL_CSP_DEC_V01_Q'+String(n).padStart(2,'0')+'_VRAI']),scoreVars);assert.strictEqual(scoreVars.score,25);for(let i=1;i<=5;i++)assert.strictEqual(scoreVars['score_t'+i],5);console.log('Bilans : scores sur 25, scores thématiques et ordre des priorités vérifiés avec le moteur ChatMD.');
