const {JSDOM}=require(process.env.CIVICOACH_JSDOM_PATH||'jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');
const base=path.resolve(__dirname,'..');const pause=n=>new Promise(r=>setTimeout(r,n));
async function start(saved=null){
 const html=fs.readFileSync(base+'/chatbot/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
 const dom=new JSDOM(html,{url:'http://localhost/chatbot/#http://localhost/chat_bot.md',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;const errors=[];w.addEventListener('error',e=>errors.push(e.message));w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent},set(v){this.textContent=v}});
 w.localStorage.setItem('civicoach-accessibilite-v1',JSON.stringify({motion:true}));if(saved)w.localStorage.setItem('novafrate-civique-v14',JSON.stringify(saved));
 w.fetch=async url=>{const u=new URL(url,w.location.href),file=path.resolve(base,'.'+u.pathname);if(!file.startsWith(base+'/'))throw Error('Unexpected URL');return new Response(fs.readFileSync(file),{status:200,headers:{'content-type':file.endsWith('.json')?'application/json':'text/plain'}});};w.speechSynthesis={cancel(){},getVoices:()=>[],speak(u){w.spoken=(w.spoken||[]).concat(u.text);setTimeout(()=>u.onend?.(),0);},pause(){},resume(){}};w.SpeechSynthesisUtterance=class{constructor(t){this.text=t}};
 for(const f of [...fs.readFileSync(base+'/chatbot/index.html','utf8').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1].split('?')[0]).concat('chatmd.js'))w.eval(fs.readFileSync(base+'/chatbot/'+f,'utf8'));
 const deadline=Date.now()+45000;while(!w.NovaRuntime||!w.document.querySelector('#chat .bot-message .messageOptions')){if(Date.now()>deadline)throw Error('ChatMD did not start: '+errors.join(';'));await pause(100);}
 await pause(200);assert.equal(errors.length,0,errors.join(';'));return {dom,w,errors};
}
(async()=>{
const {dom,w,errors}=await start();const d=w.document;
// One settings panel, same switches, can open and close without navigation.
const before=JSON.stringify(w.NovaSave.exportData().variables);const gear=d.getElementById('civi-settings-open');assert(gear);gear.click();assert(d.getElementById('civi-settings-dialog').open);assert.equal(d.querySelectorAll('#a11y-panel').length,1);assert(d.getElementById('civi-settings-dialog').contains(d.getElementById('a11y-panel')));d.getElementById('a11y-large').click();assert(w.NovaAccess.settings().large);d.getElementById('civi-settings-close').click();assert(!d.getElementById('civi-settings-dialog').open);assert.equal(JSON.stringify(w.NovaSave.exportData().variables),before);
// Topic-specific error with real chosen and correct answer.
const key=Object.keys(w.CiviFeedbackData.questions).find(k=>!w.CiviFeedbackData.questions[k].ambiguousLegacy&&w.CiviFeedbackData.questions[k].question==='Quel est le rôle du Premier ministre ?');const q=w.CiviFeedbackData.questions[key];assert(q.notion.includes('rôle du Premier ministre'));const v={trainMistakes:'|'+key+'|',trainFeedbackChoices:JSON.stringify({[key]:'Choix de test'}),trainT2:9,trainTotal2:10};w.NovaSave.importData({...w.NovaSave.exportData(),variables:v},true);
const host=d.createElement('div');host.className='message bot-message';host.innerHTML='<div class="civi-feedback" data-kind="entrainement" data-theme="2"></div>';d.getElementById('chat').append(host);w.NovaFeedback.render(host);assert(host.textContent.includes('Vous vous êtes trompé sur le rôle du Premier ministre'));assert(host.querySelector('.civi-badge').textContent.includes('Guide des institutions'));const list=host.querySelector('ol');assert(!list.textContent.includes('Quel est le rôle du Premier ministre ?'));assert(list.textContent.includes('2/2'));assert(list.textContent.includes('10/10'));host.querySelector('.civi-review-errors').click();assert(host.querySelector('details').open);assert(host.querySelector('details').textContent.includes(q.correct));assert.equal(host.querySelectorAll('a').length,0);assert(host.querySelector('.civi-chapter-advice').textContent.includes('chapitre'));
// Prefill picks the newest result for this exam only; score zero also valid.
const st=w.NovaSave.exportData();st.history.bilan=[{date:'2026-10-09T09:00:00Z',max:25,score:19,variables:{parcoursExam:'NAT'}},{date:'2026-10-09T10:00:00Z',max:25,score:25,variables:{parcoursExam:'CR'}},{date:'2026-10-08T09:00:00Z',max:25,score:7,variables:{parcoursExam:'NAT'}}];st.variables.type_examen='NAT';w.NovaSave.importData(st,true);await w.NovaRuntime.navigate('SCR_BIL_PROG_SCORE');await pause(180);const select=[...d.querySelectorAll('#score_precedent')].at(-1);assert.equal(select.value,'19');assert.equal(w.NovaSave.exportData().variables.score_precedent,'19');assert(d.querySelector('.civi-prior-score').textContent.includes('19/25'));select.value='5';select.dispatchEvent(new w.Event('change',{bubbles:true}));await pause(160);assert.equal(w.NovaSave.exportData().variables.score_precedent,'5');assert.equal(w.NovaPriorBilan.latest('CSP',st.history.bilan),null);assert.equal(w.NovaPriorBilan.latest('NAT',[{date:'2026-10-09',max:25,score:0,variables:{parcoursExam:'NAT'}}]).score,0);
assert.equal(errors.length,0,errors.join(';'));dom.window.close();console.log('PASS settings dialog, same live switches/context, precise prime-minister error, no duplicate questions in plan, badge, dual goals, open corrections, latest matching exam score and manual override');
})().catch(e=>{console.error(e);process.exit(1)});
